// Copyright 2026 ResQ
// SPDX-License-Identifier: Apache-2.0

/**
 * ResQ icon system — powered by @phosphor-icons/react.
 *
 * All icons follow the Phosphor naming convention (`*Icon` suffix).
 * The `weight` prop controls stroke weight: "thin" | "light" | "regular" | "bold" | "fill" | "duotone".
 * Default weight is "light" (matches the ResQ design system baseline).
 *
 * Re-exported types:
 * - `Icon`       — the base ForwardRefExoticComponent type for all icons
 * - `IconProps`  — props accepted by every icon (weight, size, color, className, …)
 * - `IconWeight` — the union of allowed weight strings
 *
 * Server Components: import from `@resq-sw/ui/icons/ssr` instead to avoid
 * the React.createContext call at module-init time.
 */

// ── Types ─────────────────────────────────────────────────────────────────────
export type { Icon, IconProps, IconWeight } from "@phosphor-icons/react";

// ── Navigation & chrome ───────────────────────────────────────────────────────
// UI shell controls, directional arrows, overflow menus, view toggles
export {
	AlignBottomIcon,
	AlignCenterHorizontalIcon,
	AlignCenterVerticalIcon,
	AlignLeftIcon,
	AlignRightIcon,
	AlignTopIcon,
	ArrowBendDownLeftIcon,
	ArrowBendDownRightIcon,
	ArrowBendRightDownIcon,
	ArrowBendRightUpIcon,
	ArrowCircleDownIcon,
	ArrowCircleLeftIcon,
	ArrowCircleRightIcon,
	ArrowCircleUpIcon,
	ArrowDownIcon,
	ArrowLeftIcon,
	ArrowLineDownIcon,
	ArrowLineLeftIcon,
	ArrowLineRightIcon,
	ArrowLineUpIcon,
	ArrowRightIcon,
	ArrowSquareOutIcon,
	ArrowsDownUpIcon,
	ArrowsHorizontalIcon,
	ArrowsInIcon,
	ArrowsLeftRightIcon,
	ArrowsOutIcon,
	ArrowsVerticalIcon,
	ArrowUpIcon,
	CaretDownIcon,
	CaretLeftIcon,
	CaretRightIcon,
	CaretUpDownIcon,
	CaretUpIcon,
	DotsThreeIcon,
	DotsThreeVerticalIcon,
	HouseIcon,
	ListIcon,
	RowsIcon,
	SidebarSimpleIcon,
	SignOutIcon,
	SplitHorizontalIcon,
	SplitVerticalIcon,
	SquaresFourIcon,
} from "@phosphor-icons/react";

// ── Actions ───────────────────────────────────────────────────────────────────
// Verbs: things users do to content or the system
export {
	ArrowBendUpLeftIcon,
	ArrowBendUpRightIcon,
	ArrowClockwiseIcon,
	ArrowCounterClockwiseIcon,
	ArrowsClockwiseIcon,
	ArrowsCounterClockwiseIcon,
	CameraIcon,
	CameraSlashIcon,
	CheckIcon,
	ClipboardIcon,
	CopyIcon,
	CornersInIcon,
	CornersOutIcon,
	CropIcon,
	CursorClickIcon,
	CursorIcon,
	CursorTextIcon,
	DownloadIcon,
	EraserIcon,
	EyeIcon,
	EyeSlashIcon,
	FastForwardIcon,
	FlipHorizontalIcon,
	FlipVerticalIcon,
	FrameCornersIcon,
	FunnelIcon,
	HandIcon,
	HandPointingIcon,
	HandTapIcon,
	MagnifyingGlassIcon,
	MagnifyingGlassMinusIcon,
	MagnifyingGlassPlusIcon,
	PauseIcon,
	PencilIcon,
	PlayIcon,
	PlusIcon,
	RecordIcon,
	RepeatIcon,
	RewindIcon,
	ScissorsIcon,
	ShuffleIcon,
	SkipBackIcon,
	SkipForwardIcon,
	SortAscendingIcon,
	SortDescendingIcon,
	StopIcon,
	SwapIcon,
	ToggleLeftIcon,
	ToggleRightIcon,
	TrashIcon,
	UploadIcon,
	UploadSimpleIcon,
	XIcon,
} from "@phosphor-icons/react";

// ── Status & feedback ─────────────────────────────────────────────────────────
// State indicators, severity levels, loading states
export {
	AlarmIcon,
	AsteriskIcon,
	CheckCircleIcon,
	CheckFatIcon,
	CheckSquareIcon,
	CircleDashedIcon,
	CircleHalfIcon,
	CircleIcon,
	CircleNotchIcon,
	DotIcon,
	DotOutlineIcon,
	DotsNineIcon,
	DotsSixIcon,
	HourglassIcon,
	HourglassMediumIcon,
	InfinityIcon,
	InfoIcon,
	MetronomeIcon,
	MinusIcon,
	ProhibitIcon,
	ProhibitInsetIcon,
	PulseIcon,
	QuestionIcon,
	SpinnerGapIcon,
	SpinnerIcon,
	SquareIcon,
	WarningCircleIcon,
	WarningDiamondIcon,
	WarningIcon,
	WarningOctagonIcon,
	XCircleIcon,
} from "@phosphor-icons/react";

// ── Communication ─────────────────────────────────────────────────────────────
// Messaging, alerts, voice, video, sharing, connectivity
export {
	AtIcon,
	BellIcon,
	BellRingingIcon,
	BellSlashIcon,
	BluetoothConnectedIcon,
	BluetoothSlashIcon,
	BroadcastIcon,
	CellTowerIcon,
	ChatCircleIcon,
	ChatDotsIcon,
	ChatSlashIcon,
	ChatTextIcon,
	ChatsTeardropIcon,
	EnvelopeIcon,
	DiscordLogoIcon,
	FacebookLogoIcon,
	HeadphonesIcon,
	HeadsetIcon,
	InstagramLogoIcon,
	LinkedinLogoIcon,
	MegaphoneIcon,
	MicrophoneIcon,
	MusicNoteIcon,
	MusicNotesIcon,
	PaperPlaneTiltIcon,
	PhoneIcon,
	PlayCircleIcon,
	PlayPauseIcon,
	PlaylistIcon,
	RadioIcon,
	RssIcon,
	ShareNetworkIcon,
	SlackLogoIcon,
	SpeakerHighIcon,
	SpeakerLowIcon,
	SpeakerNoneIcon,
	SpeakerSlashIcon,
	SubtitlesIcon,
	TelegramLogoIcon,
	TwitterLogoIcon,
	VideoCameraIcon,
	VideoCameraSlashIcon,
	WaveformIcon,
	WhatsappLogoIcon,
} from "@phosphor-icons/react";

// ── Emergency & field ops ─────────────────────────────────────────────────────
// ResQ domain: incident response, fleet, dispatch, triage, weather, hazmat, buildings
export {
	AirplaneInFlightIcon,
	AirplaneLandingIcon,
	AirplaneTakeoffIcon,
	AirplaneTiltIcon,
	AirTrafficControlIcon,
	AmbulanceIcon,
	AnchorIcon,
	AxeIcon,
	BandaidsIcon,
	BarbellIcon,
	BedIcon,
	BirdIcon,
	BinocularsIcon,
	BiohazardIcon,
	BankIcon,
	BoatIcon,
	BoneIcon,
	BridgeIcon,
	BuildingApartmentIcon,
	BuildingOfficeIcon,
	BuildingsIcon,
	BusIcon,
	CampfireIcon,
	CarIcon,
	CarSimpleIcon,
	CloudFogIcon,
	CloudLightningIcon,
	CloudRainIcon,
	CloudSnowIcon,
	CloudSunIcon,
	CompassIcon,
	CompassRoseIcon,
	CraneIcon,
	CrosshairIcon,
	DnaIcon,
	DogIcon,
	DoorIcon,
	DroneIcon,
	DropIcon,
	EyeClosedIcon,
	EyeglassesIcon,
	FalloutShelterIcon,
	FactoryIcon,
	FeatherIcon,
	FireExtinguisherIcon,
	FireIcon,
	FirstAidIcon,
	FishIcon,
	FootballIcon,
	FirstAidKitIcon,
	FlagBannerIcon,
	FlagCheckeredIcon,
	FlagIcon,
	FlagPennantIcon,
	FlameIcon,
	FlashlightIcon,
	FireTruckIcon,
	GarageIcon,
	GhostIcon,
	GpsFixIcon,
	GpsSlashIcon,
	HandHeartIcon,
	HandshakeIcon,
	HeartbeatIcon,
	HeartBreakIcon,
	HeartIcon,
	HospitalIcon,
	HurricaneIcon,
	LadderIcon,
	LifebuoyIcon,
	LeafIcon,
	LighthouseIcon,
	LightningIcon,
	MapPinIcon,
	MaskHappyIcon,
	MicroscopeIcon,
	MoonIcon,
	MotorcycleIcon,
	MountainsIcon,
	NavigationArrowIcon,
	PathIcon,
	PersonArmsSpreadIcon,
	PersonSimpleBikeIcon,
	PersonSimpleHikeIcon,
	PersonSimpleRunIcon,
	PersonSimpleSkiIcon,
	PersonSimpleSwimIcon,
	PersonSimpleWalkIcon,
	PillIcon,
	PoliceCarIcon,
	NeedleIcon,
	RadioactiveIcon,
	RoadHorizonIcon,
	RocketIcon,
	RocketLaunchIcon,
	SirenIcon,
	SkullIcon,
	ScooterIcon,
	SoccerBallIcon,
	SnowflakeIcon,
	StairsIcon,
	StethoscopeIcon,
	SuitcaseIcon,
	SuitcaseRollingIcon,
	SunIcon,
	SyringeIcon,
	TargetIcon,
	TestTubeIcon,
	ThermometerColdIcon,
	ThermometerHotIcon,
	ThermometerIcon,
	ThumbsDownIcon,
	ThumbsUpIcon,
	TimerIcon,
	TornadoIcon,
	TruckIcon,
	WavesIcon,
	StorefrontIcon,
	TentIcon,
	TruckTrailerIcon,
	VanIcon,
	WarehouseIcon,
	UmbrellaIcon,
	VirusIcon,
	WheelchairIcon,
	WindIcon,
	YinYangIcon,
} from "@phosphor-icons/react";

// ── Identity & security ───────────────────────────────────────────────────────
// Authentication, verification, access control, trust signals
export {
	AddressBookIcon,
	DetectiveIcon,
	FingerprintIcon,
	IdentificationCardIcon,
	KeyholeIcon,
	KeyIcon,
	LockIcon,
	LockOpenIcon,
	QrCodeIcon,
	SealCheckIcon,
	ShieldCheckIcon,
	ShieldChevronIcon,
	ShieldIcon,
	ShieldPlusIcon,
	ShieldSlashIcon,
	ShieldWarningIcon,
	UserRectangleIcon,
	UserSquareIcon,
} from "@phosphor-icons/react";

// ── Data, content & files ─────────────────────────────────────────────────────
// Records, analytics, documents, links, people, geography
export {
	ArticleIcon,
	BookmarkIcon,
	CalculatorIcon,
	BookOpenIcon,
	BrainIcon,
	CalendarBlankIcon,
	CalendarCheckIcon,
	CalendarDotsIcon,
	CalendarIcon,
	CalendarPlusIcon,
	CalendarStarIcon,
	CalendarXIcon,
	ChartBarHorizontalIcon,
	ChartBarIcon,
	ChartDonutIcon,
	ChartLineIcon,
	ChartPieIcon,
	ChartScatterIcon,
	CreditCardIcon,
	ClipboardTextIcon,
	ClockAfternoonIcon,
	ClockClockwiseIcon,
	ClockCountdownIcon,
	ClockCounterClockwiseIcon,
	ClockIcon,
	ClockUserIcon,
	ColumnsPlusLeftIcon,
	ColumnsPlusRightIcon,
	ColumnsIcon,
	CurrencyCircleDollarIcon,
	DatabaseIcon,
	FileArrowDownIcon,
	FileArrowUpIcon,
	FileCloudIcon,
	FileCodeIcon,
	FileCsvIcon,
	FileDocIcon,
	FileHtmlIcon,
	FileImageIcon,
	FileJsIcon,
	FileLockIcon,
	FileMdIcon,
	FileMinusIcon,
	FilePdfIcon,
	FilePlusIcon,
	FilePyIcon,
	FileRsIcon,
	FileTextIcon,
	FileTsIcon,
	FileVueIcon,
	FileXlsIcon,
	FileZipIcon,
	FloppyDiskIcon,
	FolderIcon,
	FolderOpenIcon,
	GlobeIcon,
	HashIcon,
	LinkBreakIcon,
	LinkIcon,
	ListBulletsIcon,
	ListChecksIcon,
	ListDashesIcon,
	ListNumbersIcon,
	MapPinAreaIcon,
	MapPinLineIcon,
	MapPinPlusIcon,
	MapPinSimpleIcon,
	MapTrifoldIcon,
	PackageIcon,
	PercentIcon,
	PiggyBankIcon,
	PresentationIcon,
	PresentationChartIcon,
	PushPinIcon,
	ReceiptIcon,
	RulerIcon,
	NoteIcon,
	NotebookIcon,
	NotePencilIcon,
	PenIcon,
	PenNibIcon,
	SignatureIcon,
	ScalesIcon,
	ShoppingBagIcon,
	ShoppingCartIcon,
	StarIcon,
	TableIcon,
	TagIcon,
	TrayArrowDownIcon,
	UserCheckIcon,
	UserCircleIcon,
	UserFocusIcon,
	UserGearIcon,
	UserIcon,
	UserListIcon,
	UserMinusIcon,
	UserPlusIcon,
	UserSwitchIcon,
	UsersIcon,
	UsersFourIcon,
	UsersThreeIcon,
	WalletIcon,
} from "@phosphor-icons/react";

// ── Infrastructure & dev ──────────────────────────────────────────────────────
// Systems, connectivity, tooling, developer workflow
export {
	AppWindowIcon,
	ArchiveIcon,
	BatteryChargingIcon,
	BatteryEmptyIcon,
	BatteryFullIcon,
	BatteryLowIcon,
	BracketsCurlyIcon,
	BracketsSquareIcon,
	BugIcon,
	BugBeetleIcon,
	CellSignalFullIcon,
	CircuitryIcon,
	CloudArrowDownIcon,
	CloudArrowUpIcon,
	CloudCheckIcon,
	CloudIcon,
	CloudWarningIcon,
	CloudXIcon,
	CodeIcon,
	CpuIcon,
	CubeIcon,
	DesktopIcon,
	FunctionIcon,
	GasPumpIcon,
	GearIcon,
	GearSixIcon,
	GitBranchIcon,
	GitCommitIcon,
	GitForkIcon,
	GitMergeIcon,
	GithubLogoIcon,
	HammerIcon,
	HardDrivesIcon,
	KeyboardIcon,
	MouseIcon,
	NetworkIcon,
	PipeWrenchIcon,
	PrinterIcon,
	PlugIcon,
	PuzzlePieceIcon,
	RobotIcon,
	SlidersHorizontalIcon,
	SolarPanelIcon,
	StackIcon,
	TelevisionIcon,
	TerminalIcon,
	TerminalWindowIcon,
	WifiHighIcon,
	WifiSlashIcon,
	WrenchIcon,
} from "@phosphor-icons/react";

// ── Text formatting ───────────────────────────────────────────────────────────
export {
	ParagraphIcon,
	QuotesIcon,
	TextAlignCenterIcon,
	TextAlignJustifyIcon,
	TextAlignLeftIcon,
	TextAlignRightIcon,
	TextBIcon,
	TextHOneIcon,
	TextHTwoIcon,
	TextHThreeIcon,
	TextIndentIcon,
	TextItalicIcon,
	TextOutdentIcon,
	TextStrikethroughIcon,
	TextUnderlineIcon,
} from "@phosphor-icons/react";
