// Copyright 2026 ResQ
// SPDX-License-Identifier: Apache-2.0

/**
 * ResQ icon system — server-component-safe variant.
 *
 * Mirrors `@resq-sw/ui/icons` but imports from `@phosphor-icons/react/ssr`,
 * which uses SSRBase instead of IconBase and therefore does NOT call
 * React.createContext() at module initialisation time.
 *
 * Use this subpath in React Server Components (Next.js App Router, etc.)
 * where the CSR variant causes "createContext is not a function" errors
 * during static page-data collection.
 *
 * Usage:
 *   import { ArrowLeftIcon } from "@resq-sw/ui/icons/ssr";
 *
 * Note: context-based theming via <IconContext.Provider> is unavailable in
 * SSRBase icons. Pass weight, size, and color as props directly.
 */

// ── Types ─────────────────────────────────────────────────────────────────────
export type { Icon, IconProps, IconWeight } from "@phosphor-icons/react";

// ── Navigation & chrome ───────────────────────────────────────────────────────
export {
	ArrowDownIcon,
	ArrowLeftIcon,
	ArrowRightIcon,
	ArrowSquareOutIcon,
	ArrowsInIcon,
	ArrowsOutIcon,
	ArrowUpIcon,
	CaretDownIcon,
	CaretLeftIcon,
	CaretRightIcon,
	CaretUpDownIcon,
	CaretUpIcon,
	DotsThreeIcon,
	DotsThreeVerticalIcon,
	HouseIcon,
	ListIcon,
	RowsIcon,
	SidebarSimpleIcon,
	SignOutIcon,
	SquaresFourIcon,
} from "@phosphor-icons/react/ssr";

// ── Actions ───────────────────────────────────────────────────────────────────
export {
	ArrowBendUpLeftIcon,
	ArrowBendUpRightIcon,
	ArrowClockwiseIcon,
	ArrowCounterClockwiseIcon,
	ArrowsClockwiseIcon,
	CheckIcon,
	ClipboardIcon,
	CopyIcon,
	CornersOutIcon,
	DownloadIcon,
	EraserIcon,
	EyeIcon,
	EyeSlashIcon,
	FastForwardIcon,
	FunnelIcon,
	HandIcon,
	HandPointingIcon,
	HandTapIcon,
	MagnifyingGlassIcon,
	PauseIcon,
	PencilIcon,
	PlayIcon,
	PlusIcon,
	RecordIcon,
	RepeatIcon,
	RewindIcon,
	ShuffleIcon,
	SkipBackIcon,
	SkipForwardIcon,
	SortAscendingIcon,
	SortDescendingIcon,
	StopIcon,
	SwapIcon,
	ToggleLeftIcon,
	ToggleRightIcon,
	TrashIcon,
	UploadIcon,
	UploadSimpleIcon,
	XIcon,
} from "@phosphor-icons/react/ssr";

// ── Status & feedback ─────────────────────────────────────────────────────────
export {
	AlarmIcon,
	CheckCircleIcon,
	CircleIcon,
	HourglassIcon,
	HourglassMediumIcon,
	InfoIcon,
	MinusIcon,
	ProhibitIcon,
	PulseIcon,
	QuestionIcon,
	SpinnerGapIcon,
	SquareIcon,
	WarningCircleIcon,
	WarningDiamondIcon,
	WarningIcon,
	WarningOctagonIcon,
	XCircleIcon,
} from "@phosphor-icons/react/ssr";

// ── Communication ─────────────────────────────────────────────────────────────
export {
	BellIcon,
	BellRingingIcon,
	BellSlashIcon,
	BluetoothConnectedIcon,
	BluetoothSlashIcon,
	BroadcastIcon,
	CellTowerIcon,
	ChatTextIcon,
	EnvelopeIcon,
	HeadsetIcon,
	MegaphoneIcon,
	MicrophoneIcon,
	PaperPlaneTiltIcon,
	PhoneIcon,
	RadioIcon,
	RssIcon,
	ShareNetworkIcon,
	VideoCameraIcon,
	VideoCameraSlashIcon,
	WaveformIcon,
} from "@phosphor-icons/react/ssr";

// ── Emergency & field ops ─────────────────────────────────────────────────────
// buildings as incident location types
export {
	AirplaneInFlightIcon,
	AirplaneLandingIcon,
	AirplaneTakeoffIcon,
	AirplaneTiltIcon,
	AirTrafficControlIcon,
	AmbulanceIcon,
	AxeIcon,
	BedIcon,
	BinocularsIcon,
	BiohazardIcon,
	BankIcon,
	BoatIcon,
	BridgeIcon,
	BuildingApartmentIcon,
	BuildingOfficeIcon,
	BuildingsIcon,
	BusIcon,
	CarIcon,
	CarSimpleIcon,
	CloudLightningIcon,
	CloudRainIcon,
	CompassIcon,
	CraneIcon,
	CrosshairIcon,
	DoorIcon,
	DroneIcon,
	DropIcon,
	FalloutShelterIcon,
	FactoryIcon,
	FireExtinguisherIcon,
	FireIcon,
	FirstAidKitIcon,
	FlagIcon,
	FlameIcon,
	FlashlightIcon,
	FireTruckIcon,
	GarageIcon,
	HandHeartIcon,
	HeartbeatIcon,
	HeartIcon,
	HospitalIcon,
	LadderIcon,
	LifebuoyIcon,
	LighthouseIcon,
	LightningIcon,
	MapPinIcon,
	MotorcycleIcon,
	MountainsIcon,
	NavigationArrowIcon,
	PathIcon,
	PersonArmsSpreadIcon,
	PersonSimpleBikeIcon,
	PersonSimpleHikeIcon,
	PersonSimpleRunIcon,
	PersonSimpleWalkIcon,
	PillIcon,
	PoliceCarIcon,
	RadioactiveIcon,
	RoadHorizonIcon,
	SirenIcon,
	SnowflakeIcon,
	StethoscopeIcon,
	SyringeIcon,
	TargetIcon,
	ThermometerIcon,
	TimerIcon,
	TornadoIcon,
	TruckIcon,
	StorefrontIcon,
	TentIcon,
	TruckTrailerIcon,
	VanIcon,
	WarehouseIcon,
	VirusIcon,
	WindIcon,
} from "@phosphor-icons/react/ssr";

// ── Identity & security ───────────────────────────────────────────────────────
export {
	FingerprintIcon,
	IdentificationCardIcon,
	KeyIcon,
	LockIcon,
	LockOpenIcon,
	QrCodeIcon,
	SealCheckIcon,
	ShieldCheckIcon,
	ShieldChevronIcon,
	ShieldIcon,
	ShieldPlusIcon,
	ShieldSlashIcon,
	ShieldWarningIcon,
} from "@phosphor-icons/react/ssr";

// ── Data, content & files ─────────────────────────────────────────────────────
export {
	BookOpenIcon,
	BrainIcon,
	CalendarBlankIcon,
	CalendarCheckIcon,
	CalendarDotsIcon,
	CalendarIcon,
	CalendarPlusIcon,
	CalendarStarIcon,
	CalendarXIcon,
	ChartBarHorizontalIcon,
	ChartBarIcon,
	ChartDonutIcon,
	ChartLineIcon,
	ChartPieIcon,
	ChartScatterIcon,
	ClipboardTextIcon,
	ClockAfternoonIcon,
	ClockClockwiseIcon,
	ClockCountdownIcon,
	ClockCounterClockwiseIcon,
	ClockIcon,
	ClockUserIcon,
	ColumnsIcon,
	CurrencyCircleDollarIcon,
	DatabaseIcon,
	FileCodeIcon,
	FileImageIcon,
	FileTextIcon,
	FolderIcon,
	FolderOpenIcon,
	GlobeIcon,
	HashIcon,
	LinkBreakIcon,
	LinkIcon,
	ListBulletsIcon,
	ListChecksIcon,
	ListDashesIcon,
	ListNumbersIcon,
	MapPinAreaIcon,
	MapPinLineIcon,
	MapPinPlusIcon,
	MapPinSimpleIcon,
	MapTrifoldIcon,
	PackageIcon,
	PercentIcon,
	PushPinIcon,
	NoteIcon,
	NotebookIcon,
	NotePencilIcon,
	PenIcon,
	PenNibIcon,
	SignatureIcon,
	StarIcon,
	TableIcon,
	TagIcon,
	TrayArrowDownIcon,
	UserCheckIcon,
	UserCircleIcon,
	UserFocusIcon,
	UserGearIcon,
	UserIcon,
	UserListIcon,
	UserMinusIcon,
	UserPlusIcon,
	UserSwitchIcon,
	UsersIcon,
	UsersFourIcon,
	UsersThreeIcon,
	WalletIcon,
} from "@phosphor-icons/react/ssr";

// ── Infrastructure & dev ──────────────────────────────────────────────────────
export {
	BatteryChargingIcon,
	BatteryEmptyIcon,
	BatteryFullIcon,
	BatteryLowIcon,
	CellSignalFullIcon,
	CloudIcon,
	CodeIcon,
	CubeIcon,
	DesktopIcon,
	GasPumpIcon,
	GearIcon,
	GearSixIcon,
	GitBranchIcon,
	GitCommitIcon,
	GitForkIcon,
	GitMergeIcon,
	GithubLogoIcon,
	HardDrivesIcon,
	NetworkIcon,
	PipeWrenchIcon,
	PlugIcon,
	PuzzlePieceIcon,
	SlidersHorizontalIcon,
	SolarPanelIcon,
	StackIcon,
	TerminalIcon,
	TerminalWindowIcon,
	WifiHighIcon,
	WifiSlashIcon,
	WrenchIcon,
} from "@phosphor-icons/react/ssr";

// ── Text formatting ───────────────────────────────────────────────────────────
export {
	TextBIcon,
	TextItalicIcon,
	TextUnderlineIcon,
} from "@phosphor-icons/react/ssr";
