/**
 * Copyright 2026 ResQ Systems, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * The repo-standard Apache-2.0 header, byte-identical to the one every other
 * TypeScript file carries.
 */
const licenseHeader = `/**
 * Copyright 2026 ResQ Systems, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
`;

/**
 * Renders the checked-in integrity module for a digest.
 *
 * The generator and the byte-for-byte determinism test both go through this one
 * renderer, so what the generator writes and what the test demands cannot drift.
 *
 * The license header is emitted deliberately. The `resq` pre-commit hook prepends
 * an Apache-2.0 header to every TypeScript file that lacks one and re-stages it,
 * which used to rewrite this generated file behind the generator's back and fail
 * the determinism test. Emitting the header up front makes that hook a no-op here.
 */
export function renderEmailContractIntegrityModule(digest: string): string {
	return `${licenseHeader}
/** Generated by scripts/generate-email-contract-integrity.ts. Do not edit. */
export const emailDesignContractIntegrity =
\t${JSON.stringify(digest)} as const;
`;
}
