/**
 * Copyright 2026 ResQ Systems, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { createHash } from "node:crypto";
import { writeFile } from "node:fs/promises";
import {
	canonicalizeEmailContract,
	emailDesignContractCore,
} from "../src/email-design-contract-core.js";

const digest = createHash("sha256")
	.update(canonicalizeEmailContract(emailDesignContractCore), "utf8")
	.digest("hex");
const output = `/** Generated by scripts/generate-email-contract-integrity.ts. Do not edit. */\nexport const emailDesignContractIntegrity =\n\t${JSON.stringify(digest)} as const;\n`;

await writeFile(
	new URL("../src/email-design-contract-integrity.ts", import.meta.url),
	output,
	"utf8",
);
