/** Generated by scripts/generate-email-contract-integrity.ts. Do not edit. */
export const emailDesignContractIntegrity =
	"770bb8af59e438a240a73bbb2f69e43fc09a32625e400c0d6c3ed60c9985c959" as const;
