/** Generated by scripts/generate-email-contract-integrity.ts. Do not edit. */
export const emailDesignContractIntegrity =
	"239feb95c270deee4b118af21785395b051e508f1a0436324930ce5ac6064c70" as const;
