/**
 * Copyright 2026 ResQ Systems, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @fileoverview Generated doctests for `packages/types/src/brand-parse.ts`.
 *
 * Every block below is a `ts doctest` fence lifted verbatim out of a JSDoc
 * example. Editing this file is pointless — edit the example it came from and
 * re-run the package's `doctest` script.
 */

// @generated by scripts/extract-doctests.ts from packages/types/src/brand-parse.ts — DO NOT EDIT.
// biome-ignore-all format: generated file — example text is reproduced verbatim from its JSDoc.
// biome-ignore-all lint: generated file — examples bind values purely to prove they type-check.

import { describe, expect, it } from "vitest";
import { BrandError, type BrandParser, brandParser } from "../../brand-parse.js";
import { type Brand, type BrandRefiner } from "../../brand.js";
import { isNarrowError } from "../../narrow.js";

describe("packages/types/src/brand-parse.ts", () => {
	// packages/types/src/brand-parse.ts:102
	it("BrandError — Reading the violated rules off a rejected value", () => {
		expect.hasAssertions();
		const Even = brandParser<number, "Even">([["even", (n) => n % 2 === 0]], "Even");

		let caught: BrandError | undefined;
		try {
		  Even.from(3);
		} catch (error) {
		  if (error instanceof BrandError) caught = error;
		}

		const stillANarrowError = isNarrowError(caught);
		expect(stillANarrowError).toStrictEqual(true);
		const brand = caught?.brand;
		expect(brand).toStrictEqual("Even");
		const failures = caught?.failures;
		expect(failures).toStrictEqual(["even"]);
		const value = caught?.value;
		expect(value).toStrictEqual(3);
		const leaksTheValue = caught?.message.includes("3");
		expect(leaksTheValue).toStrictEqual(false);
	});

	// packages/types/src/brand-parse.ts:197
	it("BrandParser — Accepting the narrow contract, supplying the wide one", () => {
		expect.hasAssertions();
		type Slug = Brand<string, "Slug">;

		const Slug: BrandParser<string, "Slug"> = brandParser<string, "Slug">(
		  [
		    ["lowercase", (s) => s === s.toLowerCase()],
		    ["no spaces", (s) => !s.includes(" ")],
		  ],
		  "Slug",
		);

		// A `BrandParser` is a `BrandRefiner`, so narrow consumers need no change.
		const refiner: BrandRefiner<string, "Slug"> = Slug;
		const accepted = refiner.is("hello-world");
		expect(accepted).toStrictEqual(true);

		// ...but the parser also says which rules were broken.
		const broken = Slug.failures("Hello World");
		expect(broken).toStrictEqual(["lowercase", "no spaces"]);
	});

	// packages/types/src/brand-parse.ts:294
	it("brandParser — An IPv4 brand that range-checks, and says which half failed", () => {
		expect.hasAssertions();
		type IPv4 = Brand<string, "IPv4">;

		const IPv4 = brandParser<string, "IPv4">(
		  [
		    ["dotted quad", (s) => /^\d{1,3}(\.\d{1,3}){3}$/.test(s)],
		    ["octet range", (s) => s.split(".").every((o) => /^\d{1,3}$/.test(o) && Number(o) <= 255)],
		  ],
		  "IPv4",
		);

		const valid = IPv4.failures("192.168.0.1").length;
		expect(valid).toStrictEqual(0);
		const outOfRange = IPv4.failures("999.0.0.1");
		expect(outOfRange).toStrictEqual(["octet range"]);
		const notAnAddress = IPv4.failures("nope");
		expect(notAnAddress).toStrictEqual(["dotted quad", "octet range"]);
	});

	// packages/types/src/brand-parse.ts:315
	it("brandParser — Branching on `parse` instead of catching", () => {
		expect.hasAssertions();
		const Password = brandParser<string, "Password">(
		  [
		    ["at least 12 characters", (s) => s.length >= 12],
		    ["contains a digit", (s) => /\d/.test(s)],
		  ],
		  "Password",
		);

		const good = Password.parse("correcthorse42");
		const accepted = good.ok ? good.value : "rejected";
		expect(accepted).toStrictEqual("correcthorse42");

		const bad = Password.parse("short");
		const why = bad.ok ? [] : bad.error.failures;
		expect(why).toStrictEqual(["at least 12 characters", "contains a digit"]);
	});
});
