/**
 * Copyright 2026 ResQ Systems, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @fileoverview Generated doctests for `packages/types/src/brand.ts`.
 *
 * Every block below is a `ts doctest` fence lifted verbatim out of a JSDoc
 * example. Editing this file is pointless — edit the example it came from and
 * re-run the package's `doctest` script.
 */

// @generated by scripts/extract-doctests.ts from packages/types/src/brand.ts — DO NOT EDIT.
// biome-ignore-all format: generated file — example text is reproduced verbatim from its JSDoc.
// biome-ignore-all lint: generated file — examples bind values purely to prove they type-check.

import { describe, expect, it } from "vitest";
import {
	type Brand,
	type BrandsOf,
	type HasBrand,
	type Unbrand,
	brandRefiner,
	refineAll,
} from "../../brand.js";

describe("packages/types/src/brand.ts", () => {
	// packages/types/src/brand.ts:118
	it("BrandsOf — Reading the brand set off a nominal type", () => {
		expect.hasAssertions();
		type Email = Brand<string, "Email">;
		type Verified = Brand<Email, "Verified">;

		const single: BrandsOf<Email> = "Email";
		expect(single).toStrictEqual("Email");
		const nested: BrandsOf<Verified>[] = ["Email", "Verified"];
		expect(nested).toStrictEqual(["Email", "Verified"]);

		// An unbranded type has no tag to match, so `BrandsOf<string>` is `never`
		// and the only inhabitant of `never[]` is the empty array.
		const unbranded: BrandsOf<string>[] = [];
		const count = unbranded.length;
		expect(count).toStrictEqual(0);
	});

	// packages/types/src/brand.ts:198
	it("Unbrand — Widening back to the carrier without a cast", () => {
		expect.hasAssertions();
		type Email = Brand<string, "Email">;
		const Email = brandRefiner<string, "Email">((s) => s.includes("@"), "email");

		// `Unbrand<Email>` is `string`, so no cast is needed at the widening boundary.
		const raw: Unbrand<Email> = Email.from("a@b.com");
		const shouted = raw.toUpperCase();
		expect(shouted).toStrictEqual("A@B.COM");
	});

	// packages/types/src/brand.ts:238
	it("HasBrand — Asserting a brand survived a composition", () => {
		expect.hasAssertions();
		type Email = Brand<string, "Email">;
		type Verified = Brand<Email, "Verified">;

		const keptEmail: HasBrand<Verified, "Email"> = true;
		expect(keptEmail).toStrictEqual(true);
		const alsoVerified: HasBrand<Verified, "Verified"> = true;
		expect(alsoVerified).toStrictEqual(true);
		const notAUserId: HasBrand<Email, "UserId"> = false;
		expect(notAUserId).toStrictEqual(false);
	});

	// packages/types/src/brand.ts:412
	it("refineAll — One constructor, two independent proofs", () => {
		expect.hasAssertions();
		type NonEmpty = Brand<string, "NonEmpty">;
		type Trimmed = Brand<string, "Trimmed">;

		const NonEmpty = brandRefiner<string, "NonEmpty">((s) => s.length > 0, "non-empty");
		const Trimmed = brandRefiner<string, "Trimmed">((s) => s === s.trim(), "trimmed");

		const Slug = refineAll(NonEmpty, Trimmed);

		// The combined value satisfies each brand on its own.
		const slug: NonEmpty & Trimmed = Slug.from("hello");
		expect(slug).toStrictEqual("hello");
		const padded = Slug.is(" hello ");
		expect(padded).toStrictEqual(false);
		const empty = Slug.coerce("");
		expect(empty).toStrictEqual(null);
	});
});
