/**
 * Copyright 2026 ResQ Systems, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @fileoverview Generated doctests for `packages/types/src/equivalence.ts`.
 *
 * Every block below is a `ts doctest` fence lifted verbatim out of a JSDoc
 * example. Editing this file is pointless — edit the example it came from and
 * re-run the package's `doctest` script.
 */

// @generated by scripts/extract-doctests.ts from packages/types/src/equivalence.ts — DO NOT EDIT.
// biome-ignore-all format: generated file — example text is reproduced verbatim from its JSDoc.
// biome-ignore-all lint: generated file — examples bind values purely to prove they type-check.

import { describe, expect, it } from "vitest";
import {
	type Equivalence,
	arrayOf,
	combine,
	combineAll,
	eqBigInt,
	eqBoolean,
	eqDate,
	eqNumber,
	eqSameValue,
	eqStrict,
	eqString,
	make,
	mapInput,
	recordOf,
	structOf,
	tupleOf,
} from "../../equivalence.js";

describe("packages/types/src/equivalence.ts", () => {
	// packages/types/src/equivalence.ts:124
	it("Equivalence — Comparing by length rather than by content", () => {
		expect.hasAssertions();
		const sameLength: Equivalence<string> = (self, that) => self.length === that.length;

		expect(sameLength("abc", "xyz")).toStrictEqual(true);
		expect(sameLength("abc", "wxyz")).toStrictEqual(false);
	});

	// packages/types/src/equivalence.ts:176
	it("make — Same user, regardless of the rest of the record", () => {
		expect.hasAssertions();
		type User = { readonly id: string; readonly name: string };

		const sameUser = make<User>((self, that) => self.id === that.id);

		expect(sameUser({ id: "u1", name: "Ada" }, { id: "u1", name: "Ada L." })).toStrictEqual(true);
		expect(sameUser({ id: "u1", name: "Ada" }, { id: "u2", name: "Ada" })).toStrictEqual(false);
	});

	// packages/types/src/equivalence.ts:189
	it("make — Reflexivity survives a deliberately broken comparison", () => {
		expect.hasAssertions();
		const broken = make<string>(() => false);

		expect(broken("a", "a")).toStrictEqual(true);
		expect(broken("a", "b")).toStrictEqual(false);
	});

	// packages/types/src/equivalence.ts:263
	it("eqStrict — Identity, and the reflexivity hole", () => {
		expect.hasAssertions();
		const strict = eqStrict<number>();

		expect(strict(1, 1)).toStrictEqual(true);
		expect(strict(0, -0)).toStrictEqual(true);
		expect(strict(Number.NaN, Number.NaN)).toStrictEqual(false);
	});

	// packages/types/src/equivalence.ts:316
	it("eqSameValue — Reflexive at `NaN`, and it splits the zeroes", () => {
		expect.hasAssertions();
		const sameValue = eqSameValue<number>();

		expect(sameValue(1, 1)).toStrictEqual(true);
		expect(sameValue(Number.NaN, Number.NaN)).toStrictEqual(true);
		expect(sameValue(0, -0)).toStrictEqual(false);
	});

	// packages/types/src/equivalence.ts:366
	it("combine — Same person by name and by age", () => {
		expect.hasAssertions();
		type Person = { readonly name: string; readonly age: number };

		const byName = mapInput(eqString, (person: Person) => person.name);
		const byAge = mapInput(eqNumber, (person: Person) => person.age);
		const samePerson = combine(byName, byAge);

		expect(samePerson({ name: "Ada", age: 36 }, { name: "Ada", age: 36 })).toStrictEqual(true);
		expect(samePerson({ name: "Ada", age: 36 }, { name: "Ada", age: 41 })).toStrictEqual(false);
	});

	// packages/types/src/equivalence.ts:421
	it("combineAll — One relation per field", () => {
		expect.hasAssertions();
		type Row = { readonly id: string; readonly rev: number };

		const sameRow = combineAll([
			mapInput(eqString, (row: Row) => row.id),
			mapInput(eqNumber, (row: Row) => row.rev),
		]);

		expect(sameRow({ id: "a", rev: 1 }, { id: "a", rev: 1 })).toStrictEqual(true);
		expect(sameRow({ id: "a", rev: 1 }, { id: "a", rev: 2 })).toStrictEqual(false);
	});

	// packages/types/src/equivalence.ts:437
	it("combineAll — The empty fold is the total relation", () => {
		expect.hasAssertions();
		const everythingIsTheSame = combineAll<string>([]);

		expect(everythingIsTheSame("a", "b")).toStrictEqual(true);
	});

	// packages/types/src/equivalence.ts:505
	it("mapInput — Case-insensitive string equivalence", () => {
		expect.hasAssertions();
		const caseInsensitive = mapInput(eqString, (value: string) => value.toLowerCase());

		expect(caseInsensitive("Hello", "HELLO")).toStrictEqual(true);
		expect(caseInsensitive("Hello", "World")).toStrictEqual(false);
	});

	// packages/types/src/equivalence.ts:553
	it("eqString — Exact string equality", () => {
		expect.hasAssertions();
		expect(eqString("abc", "abc")).toStrictEqual(true);
		expect(eqString("abc", "ABC")).toStrictEqual(false);
	});

	// packages/types/src/equivalence.ts:593
	it("eqNumber — `NaN` is reflexive, the zeroes are one value", () => {
		expect.hasAssertions();
		expect(eqNumber(1, 1)).toStrictEqual(true);
		expect(eqNumber(1, 2)).toStrictEqual(false);
		expect(eqNumber(Number.NaN, Number.NaN)).toStrictEqual(true);
		expect(eqNumber(0, -0)).toStrictEqual(true);
	});

	// packages/types/src/equivalence.ts:626
	it("eqBoolean — Boolean equality", () => {
		expect.hasAssertions();
		expect(eqBoolean(true, true)).toStrictEqual(true);
		expect(eqBoolean(true, false)).toStrictEqual(false);
	});

	// packages/types/src/equivalence.ts:661
	it("eqBigInt — BigInt equality", () => {
		expect.hasAssertions();
		expect(eqBigInt(1n, 1n)).toStrictEqual(true);
		expect(eqBigInt(1n, 2n)).toStrictEqual(false);
	});

	// packages/types/src/equivalence.ts:697
	it("eqDate — Same instant, and Invalid Dates agree", () => {
		expect.hasAssertions();
		expect(eqDate(new Date(0), new Date(0))).toStrictEqual(true);
		expect(eqDate(new Date(0), new Date(1))).toStrictEqual(false);
		expect(eqDate(new Date("nope"), new Date("also nope"))).toStrictEqual(true);
	});

	// packages/types/src/equivalence.ts:776
	it("tupleOf — A `[name, age]` pair", () => {
		expect.hasAssertions();
		const samePair = tupleOf([eqString, eqNumber]);

		expect(samePair(["Ada", 36], ["Ada", 36])).toStrictEqual(true);
		expect(samePair(["Ada", 36], ["Ada", 41])).toStrictEqual(false);
	});

	// packages/types/src/equivalence.ts:851
	it("arrayOf — Element-wise, order-sensitive, empty-safe", () => {
		expect.hasAssertions();
		const sameStrings = arrayOf(eqString);

		expect(sameStrings([], [])).toStrictEqual(true);
		expect(sameStrings(["a", "b"], ["a", "b"])).toStrictEqual(true);
		expect(sameStrings(["a", "b"], ["b", "a"])).toStrictEqual(false);
		expect(sameStrings(["a"], ["a", "b"])).toStrictEqual(false);
	});

	// packages/types/src/equivalence.ts:918
	it("structOf — Compare two fields", () => {
		expect.hasAssertions();
		const sameUser = structOf({ name: eqString, age: eqNumber });

		expect(sameUser({ name: "Ada", age: 36 }, { name: "Ada", age: 36 })).toStrictEqual(true);
		expect(sameUser({ name: "Ada", age: 36 }, { name: "Bob", age: 36 })).toStrictEqual(false);
	});

	// packages/types/src/equivalence.ts:929
	it("structOf — Unlisted fields are ignored", () => {
		expect.hasAssertions();
		const sameName = structOf({ name: eqString });
		const left = { name: "Ada", email: "ada@example.com" };
		const right = { name: "Ada", email: "lovelace@example.com" };

		expect(sameName(left, right)).toStrictEqual(true);
	});

	// packages/types/src/equivalence.ts:997
	it("recordOf — Same keys, same values, any order", () => {
		expect.hasAssertions();
		const sameScores = recordOf(eqNumber);

		expect(sameScores({}, {})).toStrictEqual(true);
		expect(sameScores({ a: 1, b: 2 }, { b: 2, a: 1 })).toStrictEqual(true);
		expect(sameScores({ a: 1 }, { a: 1, b: 2 })).toStrictEqual(false);
	});
});
