/**
 * Copyright 2026 ResQ Systems, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @fileoverview Generated doctests for `packages/types/src/filter.ts`.
 *
 * Every block below is a `ts doctest` fence lifted verbatim out of a JSDoc
 * example. Editing this file is pointless — edit the example it came from and
 * re-run the package's `doctest` script.
 */

// @generated by scripts/extract-doctests.ts from packages/types/src/filter.ts — DO NOT EDIT.
// biome-ignore-all format: generated file — example text is reproduced verbatim from its JSDoc.
// biome-ignore-all lint: generated file — examples bind values purely to prove they type-check.

import { describe, expect, it } from "vitest";
import {
	type Filter,
	compose,
	fromMaybe,
	fromPredicate,
	fromThrowing,
	make,
	mapFail,
	mapPass,
	or,
	toPredicate,
	toUndefined,
} from "../../filter.js";
import { isNumber, isString } from "../../guards.js";
import { NarrowError, type NarrowResult, tryNarrow } from "../../narrow.js";

describe("packages/types/src/filter.ts", () => {
	// packages/types/src/filter.ts:51
	it("Module — Building a case split once, then pointing it at two consumers", () => {
		expect.hasAssertions();
		const asPort = compose(
		  fromPredicate(isString),
		  fromMaybe((raw: string) => {
		    const port = Number.parseInt(raw, 10);
		    return Number.isInteger(port) && port > 0 && port < 65536 ? port : undefined;
		  }),
		);

		// Consumer one: a default, no reason needed.
		const read = toUndefined(asPort);
		const port = read("8080") ?? 443;
		expect(port).toStrictEqual(8080);
		const fallback = read("nope") ?? 443;
		expect(fallback).toStrictEqual(443);

		// Consumer two: the same case split, re-pointed at a structured error.
		const parsePort = mapFail(asPort, (input) => new NarrowError("Expected a port", { value: input }));
		const result = parsePort(0);
		const reason = result.ok ? "accepted" : result.error.message;
		expect(reason).toStrictEqual("Expected a port");
	});

	// packages/types/src/filter.ts:144
	it("Filter — Both branches, both typed", () => {
		expect.hasAssertions();
		const keepString: Filter<unknown, string, unknown> = fromPredicate(isString);

		const passed = keepString("ada");
		expect(passed).toStrictEqual({ ok: true, value: "ada" });
		const failed = keepString(42);
		expect(failed).toStrictEqual({ ok: false, error: 42 });
	});

	// packages/types/src/filter.ts:190
	it("make — A case split that computes both branches", () => {
		expect.hasAssertions();
		const evenLength = make(
		  (input: string): NarrowResult<number, string> =>
		    input.length % 2 === 0 ? { ok: true, value: input.length } : { ok: false, error: input },
		);

		const even = evenLength("abcd");
		expect(even).toStrictEqual({ ok: true, value: 4 });
		const odd = evenLength("abc");
		expect(odd).toStrictEqual({ ok: false, error: "abc" });
	});

	// packages/types/src/filter.ts:249
	it("fromPredicate — A guard's rejection branch arrives pre-narrowed", () => {
		expect.hasAssertions();
		const asString = fromPredicate(isString);

		const kept = asString("ada");
		expect(kept).toStrictEqual({ ok: true, value: "ada" });
		const rejected = asString(7);
		expect(rejected).toStrictEqual({ ok: false, error: 7 });

		// A plain predicate proves nothing, so both branches carry the input.
		const isShort = fromPredicate((value: string) => value.length < 4);
		const short = isShort("abc");
		expect(short).toStrictEqual({ ok: true, value: "abc" });
		const long = isShort("abcd");
		expect(long).toStrictEqual({ ok: false, error: "abcd" });
	});

	// packages/types/src/filter.ts:322
	it("fromMaybe — Adapting a lenient parser", () => {
		expect.hasAssertions();
		const parsePort = fromMaybe((raw: string) => {
		  const port = Number.parseInt(raw, 10);
		  return Number.isInteger(port) && port > 0 && port < 65536 ? port : undefined;
		});

		const ok = parsePort("8080");
		expect(ok).toStrictEqual({ ok: true, value: 8080 });
		const bad = parsePort("nope");
		expect(bad).toStrictEqual({ ok: false, error: "nope" });
	});

	// packages/types/src/filter.ts:380
	it("fromThrowing — Making `JSON.parse` total", () => {
		expect.hasAssertions();
		const parseJson = fromThrowing((raw: string): unknown => JSON.parse(raw));

		const ok = parseJson('{"id":1}');
		expect(ok).toStrictEqual({ ok: true, value: { id: 1 } });
		const bad = parseJson("not json");
		expect(bad).toStrictEqual({ ok: false, error: "not json" });
	});

	// packages/types/src/filter.ts:442
	it("mapPass — Reshaping what survives", () => {
		expect.hasAssertions();
		const shout = mapPass(fromPredicate(isString), (value) => value.toUpperCase());

		const loud = shout("ada");
		expect(loud).toStrictEqual({ ok: true, value: "ADA" });
		const untouched = shout(42);
		expect(untouched).toStrictEqual({ ok: false, error: 42 });
	});

	// packages/types/src/filter.ts:504
	it("mapFail — Rejection payload to structured error", () => {
		expect.hasAssertions();
		const asString = mapFail(
		  fromPredicate(isString),
		  (input) => new NarrowError("Expected string", { value: input, expected: "string" }),
		);

		const result = asString(42);
		const reason = result.ok ? "accepted" : result.error.message;
		expect(reason).toStrictEqual("Expected string");
		const offending = result.ok ? undefined : result.error.value;
		expect(offending).toStrictEqual(42);
	});

	// packages/types/src/filter.ts:565
	it("or — Accepting either of two shapes", () => {
		expect.hasAssertions();
		const stringOrNumber = or(fromPredicate(isString), fromPredicate(isNumber));

		const left = stringOrNumber("ada");
		expect(left).toStrictEqual({ ok: true, value: "ada" });
		const right = stringOrNumber(42);
		expect(right).toStrictEqual({ ok: true, value: 42 });
		const neither = stringOrNumber(true);
		expect(neither).toStrictEqual({ ok: false, error: true });
	});

	// packages/types/src/filter.ts:629
	it("compose — Prove a string, then parse it", () => {
		expect.hasAssertions();
		const asInteger = compose(
		  fromPredicate(isString),
		  fromMaybe((raw: string) => {
		    const parsed = Number.parseInt(raw, 10);
		    return Number.isNaN(parsed) ? undefined : parsed;
		  }),
		);

		const ok = asInteger("42");
		expect(ok).toStrictEqual({ ok: true, value: 42 });
		const notNumeric = asInteger("ada");
		expect(notNumeric).toStrictEqual({ ok: false, error: "ada" });
		const notString = asInteger(42);
		expect(notString).toStrictEqual({ ok: false, error: 42 });
	});

	// packages/types/src/filter.ts:701
	it("toPredicate — Feeding the decision to a builtin", () => {
		expect.hasAssertions();
		const isKept = toPredicate(fromPredicate(isString));

		const values: readonly unknown[] = ["a", 1, "b"];
		const count = values.filter(isKept).length;
		expect(count).toStrictEqual(2);
	});

	// packages/types/src/filter.ts:752
	it("toUndefined — Defaulting off a rejection", () => {
		expect.hasAssertions();
		const asString = toUndefined(fromPredicate(isString));

		const kept = asString("ada") ?? "fallback";
		expect(kept).toStrictEqual("ada");
		const dropped = asString(42) ?? "fallback";
		expect(dropped).toStrictEqual("fallback");

		// The eager counterpart, same answer.
		const eager = tryNarrow(42 as unknown, isString) ?? "fallback";
		expect(eager).toStrictEqual("fallback");
	});
});
