/**
 * Copyright 2026 ResQ Systems, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @fileoverview Generated doctests for `packages/types/src/guards.ts`.
 *
 * Every block below is a `ts doctest` fence lifted verbatim out of a JSDoc
 * example. Editing this file is pointless — edit the example it came from and
 * re-run the package's `doctest` script.
 */

// @generated by scripts/extract-doctests.ts from packages/types/src/guards.ts — DO NOT EDIT.
// biome-ignore-all format: generated file — example text is reproduced verbatim from its JSDoc.
// biome-ignore-all lint: generated file — examples bind values purely to prove they type-check.

import { describe, expect, it } from "vitest";
import {
	type NonEmptyString,
	hasKey,
	hasKeys,
	hasOwn,
	hasOwnProperty,
	isArray,
	isArrayBuffer,
	isArrayBufferView,
	isArrayLike,
	isAsyncIterable,
	isBigInt,
	isBlankString,
	isBoolean,
	isConstructor,
	isDate,
	isDefined,
	isError,
	isFiniteNumber,
	isFunction,
	isInRange,
	isInstanceOf,
	isInteger,
	isIterable,
	isJsonArray,
	isJsonObject,
	isJsonPrimitive,
	isJsonValue,
	isKeyOf,
	isMap,
	isNonEmptyArray,
	isNonEmptyString,
	isNonNull,
	isNonNullish,
	isNull,
	isNullish,
	isNumber,
	isNumericString,
	isObject,
	isObjectLike,
	isOneOf,
	isPlainObject,
	isPrimitive,
	isPromise,
	isPropertyKey,
	isRegExp,
	isSafeInteger,
	isSet,
	isString,
	isSymbol,
	isThenable,
	isTypedArray,
	isURL,
	isUint8Array,
	isUndefined,
	isValidDate,
} from "../../guards.js";

describe("packages/types/src/guards.ts", () => {
	// packages/types/src/guards.ts:50
	it("Module — Parse boundaries stop lying to you", () => {
		expect.hasAssertions();
		const latitudeOf = (raw: string): number => {
			const body: unknown = JSON.parse(raw);
			if (!isJsonObject(body)) throw new Error("expected an object");
			if (!isFiniteNumber(body.lat)) throw new Error("lat must be a real number");
			if (!isValidDate(new Date(String(body.at)))) throw new Error("unparseable timestamp");
			return body.lat;
		};

		expect(latitudeOf('{"lat":51.5,"at":"2026-01-01T00:00:00.000Z"}')).toStrictEqual(51.5);
	});

	// packages/types/src/guards.ts:164
	it("isString — Guarding a header lookup", () => {
		expect.hasAssertions();
		const headers: Record<string, unknown> = { "x-request-id": "abc" };
		const header: unknown = headers["x-request-id"];
		const id = isString(header) ? header.toUpperCase() : "unknown";

		expect(id).toStrictEqual("ABC");
	});

	// packages/types/src/guards.ts:206
	it("isNumber — The `NaN` answer, in full", () => {
		expect.hasAssertions();
		expect(isNumber(42)).toStrictEqual(true);
		expect(isNumber(Number.NaN)).toStrictEqual(true);
		expect(isNumber("42")).toStrictEqual(false);
	});

	// packages/types/src/guards.ts:238
	it("isFiniteNumber — Rejecting the two non-numbers that are `number`s", () => {
		expect.hasAssertions();
		expect(isFiniteNumber(0)).toStrictEqual(true);
		expect(isFiniteNumber(Number.NaN)).toStrictEqual(false);
		expect(isFiniteNumber(Number.POSITIVE_INFINITY)).toStrictEqual(false);
	});

	// packages/types/src/guards.ts:270
	it("isInteger — Integrality, not sign or magnitude", () => {
		expect.hasAssertions();
		expect(isInteger(-7)).toStrictEqual(true);
		expect(isInteger(2.5)).toStrictEqual(false);
		expect(isInteger(2.0)).toStrictEqual(true);
	});

	// packages/types/src/guards.ts:305
	it("isSafeInteger — Where the doubles run out", () => {
		expect.hasAssertions();
		expect(isSafeInteger(2 ** 53 - 1)).toStrictEqual(true);
		expect(isSafeInteger(2 ** 53)).toStrictEqual(false);
	});

	// packages/types/src/guards.ts:341
	it("isInRange — A reusable percentage check", () => {
		expect.hasAssertions();
		const isPercent = isInRange(0, 100);

		expect(isPercent(0)).toStrictEqual(true);
		expect(isPercent(100)).toStrictEqual(true);
		expect(isPercent(101)).toStrictEqual(false);
		expect(isPercent(Number.NaN)).toStrictEqual(false);
	});

	// packages/types/src/guards.ts:379
	it("isBoolean — Falsy is not boolean", () => {
		expect.hasAssertions();
		expect(isBoolean(false)).toStrictEqual(true);
		expect(isBoolean(0)).toStrictEqual(false);
		expect(isBoolean("true")).toStrictEqual(false);
	});

	// packages/types/src/guards.ts:411
	it("isBigInt — Distinguishing a bigint from a number", () => {
		expect.hasAssertions();
		expect(isBigInt(1n)).toStrictEqual(true);
		expect(isBigInt(1)).toStrictEqual(false);
	});

	// packages/types/src/guards.ts:442
	it("isSymbol — Well-known symbols pass, their names do not", () => {
		expect.hasAssertions();
		expect(isSymbol(Symbol.iterator)).toStrictEqual(true);
		expect(isSymbol("iterator")).toStrictEqual(false);
	});

	// packages/types/src/guards.ts:468
	it("isUndefined — The two absences are not the same", () => {
		expect.hasAssertions();
		expect(isUndefined(undefined)).toStrictEqual(true);
		expect(isUndefined(null)).toStrictEqual(false);
	});

	// packages/types/src/guards.ts:500
	it("isNull — Null is not undefined", () => {
		expect.hasAssertions();
		expect(isNull(null)).toStrictEqual(true);
		expect(isNull(undefined)).toStrictEqual(false);
	});

	// packages/types/src/guards.ts:533
	it("isPropertyKey — From an unknown key to a safe read", () => {
		expect.hasAssertions();
		const payload: unknown = { id: "abc" };
		const key: unknown = "id";
		const found = isPropertyKey(key) && hasKey(payload, key) ? payload[key] : undefined;

		expect(found).toStrictEqual("abc");
	});

	// packages/types/src/guards.ts:568
	it("isPrimitive — Collecting the leaves of an object graph", () => {
		expect.hasAssertions();
		const leaves: unknown[] = [];
		const walk = (node: unknown): void => {
			if (isPrimitive(node)) {
				leaves.push(node);
				return;
			}
			for (const child of Object.values(node as Record<string, unknown>)) walk(child);
		};

		walk({ a: 1, b: { c: "x" } });

		expect(leaves).toStrictEqual([1, "x"]);
	});

	// packages/types/src/guards.ts:617
	it("isNullish — The else branch keeps the useful half", () => {
		expect.hasAssertions();
		const trimmed = (maybe: string | null): string => (isNullish(maybe) ? "" : maybe.trim());

		expect(trimmed("  hi  ")).toStrictEqual("hi");
		expect(trimmed(null)).toStrictEqual("");
	});

	// packages/types/src/guards.ts:653
	it("isDefined — Filtering out only the undefined", () => {
		expect.hasAssertions();
		const xs: (number | undefined | null)[] = [1, undefined, null];

		expect(xs.filter(isDefined)).toStrictEqual([1, null]);
	});

	// packages/types/src/guards.ts:685
	it("isNonNull — Filtering out only the nulls", () => {
		expect.hasAssertions();
		const xs: (string | null | undefined)[] = ["a", null, undefined];

		expect(xs.filter(isNonNull)).toStrictEqual(["a", undefined]);
	});

	// packages/types/src/guards.ts:722
	it("isNonNullish — Compacting a projection", () => {
		expect.hasAssertions();
		const rows: { id: string | null }[] = [{ id: "a" }, { id: null }, { id: "b" }];

		expect(rows.map((row) => row.id).filter(isNonNullish)).toStrictEqual(["a", "b"]);
	});

	// packages/types/src/guards.ts:765
	it("NonEmptyString — A bare string is not proof", () => {
		expect.hasAssertions();
		const setDisplayName = (name: NonEmptyString): string => `Hello, ${name}`;

		const input: unknown = "Ada";
		const greeting = isNonEmptyString(input) ? setDisplayName(input) : "anonymous";

		expect(greeting).toStrictEqual("Hello, Ada");
	});

	// packages/types/src/guards.ts:798
	it("isNonEmptyString — Length, not truthiness", () => {
		expect.hasAssertions();
		expect(isNonEmptyString("0")).toStrictEqual(true);
		expect(isNonEmptyString(" ")).toStrictEqual(true);
		expect(isNonEmptyString("")).toStrictEqual(false);
	});

	// packages/types/src/guards.ts:832
	it("isBlankString — Whitespace counts as blank", () => {
		expect.hasAssertions();
		expect(isBlankString("")).toStrictEqual(true);
		expect(isBlankString("\n\t  ")).toStrictEqual(true);
		expect(isBlankString("x")).toStrictEqual(false);
		expect(isBlankString(null)).toStrictEqual(false);
	});

	// packages/types/src/guards.ts:870
	it("isNumericString — Strictly decimal", () => {
		expect.hasAssertions();
		expect(isNumericString("42")).toStrictEqual(true);
		expect(isNumericString("-1.5e3")).toStrictEqual(true);
		expect(isNumericString("")).toStrictEqual(false);
		expect(isNumericString("0x10")).toStrictEqual(false);
	});

	// packages/types/src/guards.ts:914
	it("isObject — Duck-typing a response body", () => {
		expect.hasAssertions();
		const body: unknown = JSON.parse('{"token":"abc"}');
		const token = isObject(body) && isString(body.token) ? body.token : null;

		expect(token).toStrictEqual("abc");
	});

	// packages/types/src/guards.ts:950
	it("isObjectLike — Reaching an own-property check", () => {
		expect.hasAssertions();
		const target: unknown = { id: 7 };
		const id = isObjectLike(target) && hasOwn(target, "id") ? target.id : undefined;

		expect(id).toStrictEqual(7);
	});

	// packages/types/src/guards.ts:990
	it("isPlainObject — Dictionaries only", () => {
		expect.hasAssertions();
		expect(isPlainObject({ a: 1 })).toStrictEqual(true);
		expect(isPlainObject(Object.create(null))).toStrictEqual(true);
		expect(isPlainObject([])).toStrictEqual(false);
		expect(isPlainObject(new Date())).toStrictEqual(false);
		expect(isPlainObject(new (class {})())).toStrictEqual(false);
	});

	// packages/types/src/guards.ts:1038
	it("isArray — Iterating a parsed payload", () => {
		expect.hasAssertions();
		const parsed: unknown = JSON.parse("[1,2,3]");
		const seen: unknown[] = [];
		if (isArray(parsed)) for (const item of parsed) seen.push(item);

		expect(seen).toStrictEqual([1, 2, 3]);
	});

	// packages/types/src/guards.ts:1075
	it("isNonEmptyArray — Index access without an assertion", () => {
		expect.hasAssertions();
		const first = (xs: readonly string[]): string => {
			if (!isNonEmptyArray(xs)) throw new Error("expected at least one");
			return xs[0];
		};

		expect(first(["a", "b"])).toStrictEqual("a");
	});

	// packages/types/src/guards.ts:1112
	it("isArrayLike — Indexing anything array-shaped", () => {
		expect.hasAssertions();
		const collect = (input: unknown): unknown[] => {
			if (!isArrayLike(input)) return [];
			const out: unknown[] = [];
			for (let i = 0; i < input.length; i += 1) out.push(input[i]);
			return out;
		};

		expect(collect("abc")).toStrictEqual(["a", "b", "c"]);
	});

	// packages/types/src/guards.ts:1159
	it("isIterable — Normalizing one-or-many", () => {
		expect.hasAssertions();
		const toArray = (input: unknown): unknown[] => (isIterable(input) ? [...input] : [input]);

		expect(toArray(new Set([1, 2]))).toStrictEqual([1, 2]);
		expect(toArray(7)).toStrictEqual([7]);
	});

	// packages/types/src/guards.ts:1199
	it("isAsyncIterable — Telling a stream from a collection", () => {
		expect.hasAssertions();
		async function* frames(): AsyncGenerator<number> {
			yield 1;
		}

		expect(isAsyncIterable(frames())).toStrictEqual(true);
		expect(isAsyncIterable([1, 2])).toStrictEqual(false);
	});

	// packages/types/src/guards.ts:1247
	it("isMap — Tag plus internal slot", () => {
		expect.hasAssertions();
		expect(isMap(new Map([["a", 1]]))).toStrictEqual(true);
		expect(isMap({ [Symbol.toStringTag]: "Map" })).toStrictEqual(false);
	});

	// packages/types/src/guards.ts:1283
	it("isSet — An allow-list check that survives a realm hop", () => {
		expect.hasAssertions();
		const allowed: unknown = new Set(["https://example.com"]);

		expect(isSet(allowed) && allowed.has("https://example.com")).toStrictEqual(true);
	});

	// packages/types/src/guards.ts:1323
	it("isFunction — Arbitrary arguments still allowed", () => {
		expect.hasAssertions();
		const handler: unknown = (a: number, b: number) => a + b;
		const result = isFunction(handler) ? handler(2, 3) : undefined;

		expect(result).toStrictEqual(5);
	});

	// packages/types/src/guards.ts:1366
	it("isConstructor — Arrows have no `[[Construct]]`", () => {
		expect.hasAssertions();
		class Service {}

		expect(isConstructor(Service)).toStrictEqual(true);
		expect(isConstructor(() => {})).toStrictEqual(false);
	});

	// packages/types/src/guards.ts:1412
	it("isPromise — Thenables count, plain objects do not", () => {
		expect.hasAssertions();
		expect(isPromise(Promise.resolve(1))).toStrictEqual(true);
		expect(isPromise({ then: () => {} })).toStrictEqual(true);
		expect(isPromise({})).toStrictEqual(false);
	});

	// packages/types/src/guards.ts:1449
	it("isThenable — Branching on awaitability", () => {
		expect.hasAssertions();
		const kindOf = (x: unknown): unknown => (isThenable(x) ? "awaitable" : x);

		expect(kindOf(Promise.resolve(1))).toStrictEqual("awaitable");
		expect(kindOf(7)).toStrictEqual(7);
	});

	// packages/types/src/guards.ts:1492
	it("isDate — A `Date` is a `Date` even when it is nonsense", () => {
		expect.hasAssertions();
		expect(isDate(new Date())).toStrictEqual(true);
		expect(isDate(Date.now())).toStrictEqual(false);
		expect(isDate(new Date("nope"))).toStrictEqual(true);
		expect(isDate({ [Symbol.toStringTag]: "Date" })).toStrictEqual(false);
	});

	// packages/types/src/guards.ts:1539
	it("isValidDate — `toISOString` cannot throw after this", () => {
		expect.hasAssertions();
		const stamp = (input: string): string => {
			const at = new Date(input);
			if (!isValidDate(at)) throw new Error(`unparseable timestamp: ${input}`);
			return at.toISOString();
		};

		expect(stamp("2026-01-01T00:00:00.000Z")).toStrictEqual("2026-01-01T00:00:00.000Z");
		expect(isValidDate(new Date("nope"))).toStrictEqual(false);
	});

	// packages/types/src/guards.ts:1587
	it("isRegExp — Only a real pattern has a real `source`", () => {
		expect.hasAssertions();
		const pattern: unknown = /^a+$/u;

		expect(isRegExp(pattern) ? pattern.source : "").toStrictEqual("^a+$");
		expect(isRegExp({ source: "^a+$" })).toStrictEqual(false);
	});

	// packages/types/src/guards.ts:1628
	it("isError — Logging a cause without losing it", () => {
		expect.hasAssertions();
		const describeCause = (cause: unknown): string =>
			isError(cause) ? cause.message : String(cause);

		expect(describeCause(new TypeError("bad input"))).toStrictEqual("bad input");
		expect(describeCause("boom")).toStrictEqual("boom");
	});

	// packages/types/src/guards.ts:1667
	it("isURL — Enforcing a scheme", () => {
		expect.hasAssertions();
		const target: unknown = new URL("https://example.com/path");

		expect(isURL(target) ? target.protocol : "").toStrictEqual("https:");
		expect(isURL({ href: "https://example.com/" })).toStrictEqual(false);
	});

	// packages/types/src/guards.ts:1713
	it("isArrayBufferView — Both halves of the family pass", () => {
		expect.hasAssertions();
		expect(isArrayBufferView(new Uint8Array(1))).toStrictEqual(true);
		expect(isArrayBufferView(new DataView(new ArrayBuffer(8)))).toStrictEqual(true);
		expect(isArrayBufferView(new ArrayBuffer(8))).toStrictEqual(false);
	});

	// packages/types/src/guards.ts:1751
	it("isTypedArray — The one `ArrayBufferView` that is excluded", () => {
		expect.hasAssertions();
		expect(isTypedArray(new Uint8Array(1))).toStrictEqual(true);
		expect(isTypedArray(new DataView(new ArrayBuffer(8)))).toStrictEqual(false);
		expect(isTypedArray(new ArrayBuffer(8))).toStrictEqual(false);
	});

	// packages/types/src/guards.ts:1785
	it("isUint8Array — Rejecting the wrong element width", () => {
		expect.hasAssertions();
		expect(isUint8Array(new Uint8Array([1, 2]))).toStrictEqual(true);
		expect(isUint8Array(new Uint16Array([1, 2]))).toStrictEqual(false);
	});

	// packages/types/src/guards.ts:1818
	it("isArrayBuffer — Normalizing a chunk to bytes", () => {
		expect.hasAssertions();
		const chunk: unknown = new ArrayBuffer(2);
		const bytes = isArrayBuffer(chunk) ? new Uint8Array(chunk) : new Uint8Array(0);

		expect(bytes.byteLength).toStrictEqual(2);
		expect(isArrayBuffer(new Uint8Array(2))).toStrictEqual(false);
	});

	// packages/types/src/guards.ts:1858
	it("hasKey — Reading a message off an unknown cause", () => {
		expect.hasAssertions();
		const messageOf = (cause: unknown): string =>
			hasKey(cause, "message") && isString(cause.message) ? cause.message : String(cause);

		expect(messageOf({ message: "nope" })).toStrictEqual("nope");
		expect(messageOf(42)).toStrictEqual("42");
	});

	// packages/types/src/guards.ts:1902
	it("hasKeys — All-or-nothing field presence", () => {
		expect.hasAssertions();
		const frame: unknown = { lat: 51.5, lon: -0.12, at: 0 };
		const plotted = hasKeys(frame, "lat", "lon", "at") ? [frame.lat, frame.lon, frame.at] : [];

		expect(plotted).toStrictEqual([51.5, -0.12, 0]);
		expect(hasKeys(frame, "lat", "alt")).toStrictEqual(false);
	});

	// packages/types/src/guards.ts:1947
	it("hasOwn — Inherited does not count", () => {
		expect.hasAssertions();
		const config: object = { retries: 3 };

		expect(hasOwn(config, "retries") ? config.retries : 0).toStrictEqual(3);
		expect(hasOwn({}, "toString")).toStrictEqual(false);
	});

	// packages/types/src/guards.ts:1994
	it("hasOwnProperty — True, but proving nothing to the compiler", () => {
		expect.hasAssertions();
		expect(hasOwnProperty({ a: 1 }, "a")).toStrictEqual(true);
		expect(hasOwnProperty({}, "toString")).toStrictEqual(false);
	});

	// packages/types/src/guards.ts:2051
	it("isKeyOf — A config string becomes a safe index", () => {
		expect.hasAssertions();
		const palette = { primary: 1, accent: 2 } as const;
		const name: string = "accent";
		const chosen = isKeyOf(palette, name) ? palette[name] : 0;

		expect(chosen).toStrictEqual(2);
		expect(isKeyOf(palette, "toString")).toStrictEqual(false);
	});

	// packages/types/src/guards.ts:2096
	it("isOneOf — Parsing a log level with a fallback", () => {
		expect.hasAssertions();
		const isLevel = isOneOf("debug", "info", "warn", "error");
		const raw: unknown = "warn";
		const level = isLevel(raw) ? raw : "info";

		expect(level).toStrictEqual("warn");
		expect(isLevel("trace")).toStrictEqual(false);
	});

	// packages/types/src/guards.ts:2142
	it("isInstanceOf — Filtering a mixed array down to errors", () => {
		expect.hasAssertions();
		const results: unknown[] = [new Error("a"), "b", new TypeError("c")];

		expect(results.filter(isInstanceOf(Error)).map((error) => error.message)).toStrictEqual(["a", "c"]);
	});

	// packages/types/src/guards.ts:2187
	it("isJsonPrimitive — `bigint` is the notable exclusion", () => {
		expect.hasAssertions();
		expect(isJsonPrimitive(null)).toStrictEqual(true);
		expect(isJsonPrimitive(1n)).toStrictEqual(false);
	});

	// packages/types/src/guards.ts:2228
	it("isJsonArray — Holes do not round-trip", () => {
		expect.hasAssertions();
		expect(isJsonArray([1, "a", null, { b: [] }])).toStrictEqual(true);
		expect(isJsonArray([() => {}])).toStrictEqual(false);
		expect(isJsonArray(new Array(2))).toStrictEqual(false);
	});

	// packages/types/src/guards.ts:2282
	it("isJsonObject — A non-enumerable member is still inspected", () => {
		expect.hasAssertions();
		expect(isJsonObject({ a: 1, b: undefined })).toStrictEqual(true);
		expect(isJsonObject(new Date())).toStrictEqual(false);

		const hidden = { a: 1 };
		Object.defineProperty(hidden, "b", { value: () => {}, enumerable: false });

		expect(isJsonObject(hidden)).toStrictEqual(false);
	});

	// packages/types/src/guards.ts:2340
	it("isJsonValue — Proving a payload is cacheable", () => {
		expect.hasAssertions();
		const body: unknown = JSON.parse('{"a":[1,null]}');

		expect(isJsonValue(body)).toStrictEqual(true);
		expect(isJsonValue({ fn: () => {} })).toStrictEqual(false);
	});
});
