/**
 * Copyright 2026 ResQ Systems, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @fileoverview Generated doctests for `packages/types/src/index.ts`.
 *
 * Every block below is a `ts doctest` fence lifted verbatim out of a JSDoc
 * example. Editing this file is pointless — edit the example it came from and
 * re-run the package's `doctest` script.
 */

// @generated by scripts/extract-doctests.ts from packages/types/src/index.ts — DO NOT EDIT.
// biome-ignore-all format: generated file — example text is reproduced verbatim from its JSDoc.
// biome-ignore-all lint: generated file — examples bind values purely to prove they type-check.

import { describe, expect, it } from "vitest";
import { ensure, isNonEmptyString, matchTag } from "../../index.js";

describe("packages/types/src/index.ts", () => {
	// packages/types/src/index.ts:93
	it("Module — Reaching every module through the one barrel specifier", () => {
		expect.hasAssertions();
		const raw: unknown = "ada";
		const name = ensure(raw, isNonEmptyString);

		expect(name.length).toStrictEqual(3);

		type Event = { kind: "click"; x: number } | { kind: "key"; code: string };

		const describe = (event: Event): string =>
		  matchTag(event, "kind", {
		    click: (member) => `click@${member.x}`,
		    key: (member) => `key:${member.code}`,
		  });

		expect(describe({ kind: "key", code: "Escape" })).toStrictEqual("key:Escape");
	});
});
