/**
 * Copyright 2026 ResQ Systems, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @fileoverview Generated doctests for `packages/types/src/logic.ts`.
 *
 * Every block below is a `ts doctest` fence lifted verbatim out of a JSDoc
 * example. Editing this file is pointless — edit the example it came from and
 * re-run the package's `doctest` script.
 */

// @generated by scripts/extract-doctests.ts from packages/types/src/logic.ts — DO NOT EDIT.
// biome-ignore-all format: generated file — example text is reproduced verbatim from its JSDoc.
// biome-ignore-all lint: generated file — examples bind values purely to prove they type-check.

import { describe, it } from "vitest";
import {
	type AllTrue,
	type And,
	type AnyTrue,
	type BoolEqv,
	type BoolXor,
	type Extends,
	type ExtendsDistributive,
	type If,
	type Implies,
	type IsBooleanLiteral,
	type IsEmptyObject,
	type IsEqual,
	type IsLiteral,
	type IsMutuallyAssignable,
	type IsNullable,
	type IsNumericLiteral,
	type IsOptionalKey,
	type IsPlainObject,
	type IsReadonlyKey,
	type IsStringLiteral,
	type IsSubtypeOf,
	type IsSupertypeOf,
	type IsTuple,
	type IsUndefinable,
	type Nand,
	type Nor,
	type Not,
	type Or,
} from "../../logic.js";

describe("packages/types/src/logic.ts", () => {
	// packages/types/src/logic.ts:50
	it("Module — Guarding a generic on a computed condition", () => {
		type IsReadonlyTuple<T> = And<Extends<T, readonly unknown[]>, Not<Extends<T, unknown[]>>>;

		const frozen: IsReadonlyTuple<readonly [1, 2]> = true;
		const mutable: IsReadonlyTuple<[1, 2]> = false;
	});

	// packages/types/src/logic.ts:138
	it("If — Choosing a branch on a proven condition", () => {
		const chosen: If<true, string, number> = "value";
		const otherwise: If<false, string, number> = 42;
		// An un-narrowed `boolean` is not a proven `true`, so `Else` wins.
		const unproven: If<boolean, string, number> = 42;
	});

	// packages/types/src/logic.ts:178
	it("Not — Inverting a condition", () => {
		const negated: Not<true> = false;
		const restored: Not<false> = true;
	});

	// packages/types/src/logic.ts:211
	it("And — Requiring both conditions", () => {
		const both: And<true, true> = true;
		const missingOne: And<true, false> = false;
		// An un-narrowed operand is normalized rather than leaked.
		const unproven: And<true, boolean> = false;
	});

	// packages/types/src/logic.ts:245
	it("Or — Accepting either condition", () => {
		const either: Or<false, true> = true;
		const neither: Or<false, false> = false;
	});

	// packages/types/src/logic.ts:280
	it("BoolXor — Requiring exactly one of two flags", () => {
		const differ: BoolXor<true, false> = true;
		const agree: BoolXor<true, true> = false;
	});

	// packages/types/src/logic.ts:311
	it("Nand — Forbidding the both-true case", () => {
		const bothTrue: Nand<true, true> = false;
		const notBoth: Nand<true, false> = true;
	});

	// packages/types/src/logic.ts:342
	it("Nor — Asserting that both conditions fail", () => {
		const neither: Nor<false, false> = true;
		const oneHolds: Nor<true, false> = false;
	});

	// packages/types/src/logic.ts:382
	it("BoolEqv — Requiring two conditions to agree", () => {
		const bothTrue: BoolEqv<true, true> = true;
		const bothFalse: BoolEqv<false, false> = true;
		const disagree: BoolEqv<true, false> = false;
	});

	// packages/types/src/logic.ts:417
	it("Implies — Encoding a conditional requirement", () => {
		const holds: Implies<true, true> = true;
		// The only falsifying case.
		const broken: Implies<true, false> = false;
		// A false antecedent is vacuously true.
		const vacuous: Implies<false, false> = true;
	});

	// packages/types/src/logic.ts:455
	it("AllTrue — Folding several probes into one condition", () => {
		const allHold: AllTrue<[true, true, true]> = true;
		const oneFails: AllTrue<[true, false, true]> = false;
		// Vacuously true, as an empty conjunction should be.
		const empty: AllTrue<[]> = true;
	});

	// packages/types/src/logic.ts:491
	it("AnyTrue — Asking whether any probe holds", () => {
		const someHold: AnyTrue<[false, true]> = true;
		const noneHold: AnyTrue<[false, false]> = false;
		const empty: AnyTrue<[]> = false;
	});

	// packages/types/src/logic.ts:529
	it("Extends — Testing a union as a whole", () => {
		const wholeUnionIsString: Extends<"a" | "b", string> = true;
		const widenedIsNotLiteral: Extends<string, "a"> = false;
		// The union as a whole is not a string, and the answer is definite.
		const mixedUnion: Extends<"a" | 1, string> = false;
	});

	// packages/types/src/logic.ts:573
	it("ExtendsDistributive — Contrasting the two readings", () => {
		const everyMemberIsString: ExtendsDistributive<"a" | "b", string> = true;
		// A mixed union honestly reports "some do, some do not" — i.e. `boolean`.
		const mixed: ExtendsDistributive<"a" | 1, string> = false;
		// The non-distributive form gives a definite answer for the same input.
		const asAWhole: Extends<"a" | 1, string> = false;
	});

	// packages/types/src/logic.ts:618
	it("IsEqual — Detecting a modifier difference", () => {
		const same: IsEqual<{ a: 1 }, { a: 1 }> = true;
		// `readonly` is invisible to assignability but not to identity.
		const modifierDiffers: IsEqual<{ a: 1 }, { readonly a: 1 }> = false;
	});

	// packages/types/src/logic.ts:651
	it("IsSubtypeOf — Proving a refinement narrowed", () => {
		const narrowed: IsSubtypeOf<"a", string> = true;
		// Equal is not *proper*.
		const noop: IsSubtypeOf<string, string> = false;
	});

	// packages/types/src/logic.ts:678
	it("IsSupertypeOf — Locking a widening assertion", () => {
		const widened: IsSupertypeOf<string, "a"> = true;
		const unchanged: IsSupertypeOf<string, string> = false;
	});

	// packages/types/src/logic.ts:709
	it("IsMutuallyAssignable — Compatibility versus identity", () => {
		const swappable: IsMutuallyAssignable<{ a: 1 }, { readonly a: 1 }> = true;
		// Contrast: identity sees the modifier.
		const identical: IsEqual<{ a: 1 }, { readonly a: 1 }> = false;
	});

	// packages/types/src/logic.ts:755
	it("IsStringLiteral — Telling a literal from a pattern", () => {
		const literal: IsStringLiteral<"a"> = true;
		const unionOfLiterals: IsStringLiteral<"a" | "b"> = true;
		const widened: IsStringLiteral<string> = false;
		// A pattern, not a literal — the case the naive check gets wrong.
		const pattern: IsStringLiteral<`on${string}`> = false;
	});

	// packages/types/src/logic.ts:799
	it("IsNumericLiteral — Rejecting a widened number", () => {
		const literal: IsNumericLiteral<1> = true;
		const bigLiteral: IsNumericLiteral<1n> = true;
		const widened: IsNumericLiteral<number> = false;
	});

	// packages/types/src/logic.ts:837
	it("IsBooleanLiteral — Catching an unresolved condition", () => {
		const resolvedTrue: IsBooleanLiteral<true> = true;
		const resolvedFalse: IsBooleanLiteral<false> = true;
		// The case every naive check fails.
		const unresolved: IsBooleanLiteral<boolean> = false;
	});

	// packages/types/src/logic.ts:872
	it("IsLiteral — Detecting a widened inference", () => {
		const stringLiteral: IsLiteral<"a"> = true;
		const numberLiteral: IsLiteral<42> = true;
		const booleanLiteral: IsLiteral<true> = true;
		const widened: IsLiteral<string> = false;
	});

	// packages/types/src/logic.ts:909
	it("IsTuple — Choosing a variadic policy", () => {
		const fixed: IsTuple<[1, 2]> = true;
		const unbounded: IsTuple<number[]> = false;
		// Variadic: excluded by default, included on request.
		const variadicStrict: IsTuple<[1, ...number[]]> = false;
		const variadicLoose: IsTuple<[1, ...number[]], false> = true;
	});

	// packages/types/src/logic.ts:956
	it("IsPlainObject — Guarding a recursive traversal", () => {
		const record: IsPlainObject<{ a: 1 }> = true;
		const array: IsPlainObject<number[]> = false;
		const callable: IsPlainObject<() => void> = false;
		// See the caveat: a structural check cannot exclude class instances.
		const instance: IsPlainObject<Date> = true;
	});

	// packages/types/src/logic.ts:995
	it("IsNullable — Distinguishing null from undefined", () => {
		const nullable: IsNullable<string | null> = true;
		// Not nullable by this definition — see IsUndefinable.
		const undefinable: IsNullable<string | undefined> = false;
	});

	// packages/types/src/logic.ts:1029
	it("IsUndefinable — Asking about the value, not the key", () => {
		const undefinable: IsUndefinable<string | undefined> = true;
		const nullable: IsUndefinable<string | null> = false;
	});

	// packages/types/src/logic.ts:1066
	it("IsOptionalKey — Optional key versus undefined value", () => {
		interface Config {
			readonly retries?: number;
			readonly timeout: number | undefined;
		}

		const mayBeOmitted: IsOptionalKey<Config, "retries"> = true;
		// Present-but-undefined is required, not optional.
		const required: IsOptionalKey<Config, "timeout"> = false;
	});

	// packages/types/src/logic.ts:1111
	it("IsReadonlyKey — Detecting a preserved modifier", () => {
		const frozen: IsReadonlyKey<{ readonly a: 1 }, "a"> = true;
		const mutable: IsReadonlyKey<{ a: 1 }, "a"> = false;
		// A union of keys is all-or-nothing.
		const mixed: IsReadonlyKey<{ readonly a: 1; b: 2 }, "a" | "b"> = false;
	});

	// packages/types/src/logic.ts:1155
	it("IsEmptyObject — Detecting a filtered-to-nothing shape", () => {
		const empty: IsEmptyObject<Record<never, never>> = true;
		const populated: IsEmptyObject<{ a: 1 }> = false;
		// An index signature means `keyof` is not `never`.
		const indexed: IsEmptyObject<Record<string, never>> = false;
	});
});
