/**
 * Copyright 2026 ResQ Systems, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @fileoverview Generated doctests for `packages/types/src/narrow.ts`.
 *
 * Every block below is a `ts doctest` fence lifted verbatim out of a JSDoc
 * example. Editing this file is pointless — edit the example it came from and
 * re-run the package's `doctest` script.
 */

// @generated by scripts/extract-doctests.ts from packages/types/src/narrow.ts — DO NOT EDIT.
// biome-ignore-all format: generated file — example text is reproduced verbatim from its JSDoc.
// biome-ignore-all lint: generated file — examples bind values purely to prove they type-check.

import { describe, expect, it } from "vitest";
import { isNonEmptyString, isNumericString, isPlainObject, isString } from "../../guards.js";
import {
	type Assertion,
	type NarrowError,
	type NarrowResult,
	assert,
	assertBy,
	assertDefined,
	assertExists,
	assertGuard,
	assertNonNullish,
	ensure,
	ensureDefined,
	invariant,
	isNarrowError,
	narrowAll,
	parse,
	tryNarrow,
	unsafeNarrow,
} from "../../narrow.js";

describe("packages/types/src/narrow.ts", () => {
	// packages/types/src/narrow.ts:36
	it("Module — The recommended shape", () => {
		expect.hasAssertions();
		const payload: { readonly name: unknown } = { name: "ada" };

		// Throws a NarrowError at the boundary if the guard rejects.
		const name = ensure(payload.name, isString, "name must be a string");
		const shouted = name.toUpperCase();
		expect(shouted).toStrictEqual("ADA");

		// Same parameters, same order — only the control flow differs.
		const result = parse(payload.name, isString, "name must be a string");
		const rendered = result.ok ? result.value : result.error.message;
		expect(rendered).toStrictEqual("ada");
	});

	// packages/types/src/narrow.ts:129
	it("NarrowError — Reading the structured fields off a caught failure", () => {
		expect.hasAssertions();
		const input: unknown = "";
		let caught: NarrowError | undefined;

		try {
		  ensure(input, isNonEmptyString, "display name must not be blank", "NonEmptyString");
		} catch (error) {
		  if (isNarrowError(error)) caught = error;
		}

		const message = caught?.message;
		expect(message).toStrictEqual("display name must not be blank");
		const expected = caught?.expected;
		expect(expected).toStrictEqual("NonEmptyString");
		const value = caught?.value;
		expect(value).toStrictEqual("");
	});

	// packages/types/src/narrow.ts:227
	it("isNarrowError — Handling ours, rethrowing theirs", () => {
		expect.hasAssertions();
		function readBody(body: unknown): string {
		  try {
		    ensure(body, isPlainObject, "body must be an object");
		    return "ok";
		  } catch (error) {
		    if (isNarrowError(error)) return error.message;
		    throw error; // ✓ never swallow errors you did not cause
		  }
		}

		const good = readBody({ id: 1 });
		expect(good).toStrictEqual("ok");
		const bad = readBody("nope");
		expect(bad).toStrictEqual("body must be an object");
	});

	// packages/types/src/narrow.ts:300
	it("Assertion — Annotating the const so narrowing survives", () => {
		expect.hasAssertions();
		const assertString: Assertion<unknown, string> = assertGuard(isString);

		const raw: unknown = "hello";
		assertString(raw);
		const shouted = raw.toUpperCase();
		expect(shouted).toStrictEqual("HELLO");
	});

	// packages/types/src/narrow.ts:359
	it("NarrowResult — Defaulting off the discriminant", () => {
		expect.hasAssertions();
		const input: unknown = 42;

		const result: NarrowResult<string> = parse(input, isString);
		const value = result.ok ? result.value : "fallback";
		expect(value).toStrictEqual("fallback");
	});

	// packages/types/src/narrow.ts:371
	it("NarrowResult — A failure branch that is not an error", () => {
		expect.hasAssertions();
		// The failure arm carries the rejected input, which is what `./filter` produces.
		const evenOnly = (input: number): NarrowResult<number, number> =>
		  input % 2 === 0 ? { ok: true, value: input } : { ok: false, error: input };

		const kept = evenOnly(4);
		const keptLabel = kept.ok ? `kept ${kept.value}` : `rejected ${kept.error}`;
		expect(keptLabel).toStrictEqual("kept 4");

		const dropped = evenOnly(7);
		const droppedLabel = dropped.ok ? `kept ${dropped.value}` : `rejected ${dropped.error}`;
		expect(droppedLabel).toStrictEqual("rejected 7");
	});

	// packages/types/src/narrow.ts:467
	it("ensure — Validating an environment variable at the boundary", () => {
		expect.hasAssertions();
		const raw: unknown = "8080";

		const port = ensure(raw, isNumericString, "PORT must be numeric");
		const parsed = Number(port);
		expect(parsed).toStrictEqual(8080);
	});

	// packages/types/src/narrow.ts:530
	it("ensureDefined — Replacing a non-null assertion after a cache read", () => {
		expect.hasAssertions();
		const cache = new Map<string, { readonly name: string }>([["u1", { name: "ada" }]]);

		// The bound type is the record, not `record | undefined` — and it checked.
		const user = ensureDefined(cache.get("u1"), "no cached user for u1");
		const name = user.name;
		expect(name).toStrictEqual("ada");
	});

	// packages/types/src/narrow.ts:608
	it("parse — Answering a bad webhook body instead of throwing", () => {
		expect.hasAssertions();
		const body: unknown = { event: "ping" };
		const parsed = parse(body, isPlainObject, undefined, "WebhookPayload");
		const status = parsed.ok ? "accepted" : parsed.error.message;
		expect(status).toStrictEqual("accepted");

		const junk: unknown = "nope";
		const rejected = parse(junk, isPlainObject, undefined, "WebhookPayload");
		const reason = rejected.ok ? "accepted" : rejected.error.message;
		expect(reason).toStrictEqual("Expected WebhookPayload");
	});

	// packages/types/src/narrow.ts:680
	it("tryNarrow — Falling back when stored input no longer matches the union", () => {
		expect.hasAssertions();
		type Theme = "light" | "dark";
		const isTheme = (value: unknown): value is Theme =>
		  value === "light" || value === "dark";

		const stored: unknown = "solarized";
		const theme = tryNarrow(stored, isTheme) ?? "dark";
		expect(theme).toStrictEqual("dark");
	});

	// packages/types/src/narrow.ts:731
	it("narrowAll — Accepting a JSON array only if it is homogeneous", () => {
		expect.hasAssertions();
		const raw: readonly unknown[] = ["a", "b", "c"];

		// `raw` is `readonly string[]` inside the true branch.
		const joined = narrowAll(raw, isString) ? raw.join(",") : "mixed";
		expect(joined).toStrictEqual("a,b,c");
	});

	// packages/types/src/narrow.ts:788
	it("unsafeNarrow — Trusting a driver that already guarantees the row shape", () => {
		expect.hasAssertions();
		interface UserRow {
		  readonly id: string;
		}

		const rows = unsafeNarrow<readonly UserRow[]>([{ id: "u1" }]);
		const first = rows[0]?.id;
		expect(first).toStrictEqual("u1");
	});

	// packages/types/src/narrow.ts:834
	it("assertBy — Narrowing a config object in statement position", () => {
		expect.hasAssertions();
		const config: unknown = { port: 8080 };

		assertBy(config, isPlainObject, "config must be an object");
		const port = config["port"];
		expect(port).toStrictEqual(8080);
	});

	// packages/types/src/narrow.ts:886
	it("assertDefined — Popping a queue that must not be empty", () => {
		expect.hasAssertions();
		const queue: readonly string[] = ["build", "test"];

		const first = queue[0];
		assertDefined(first, "queue was empty");
		const stage = first.toUpperCase();
		expect(stage).toStrictEqual("BUILD");
	});

	// packages/types/src/narrow.ts:933
	it("assertNonNullish — Asserting a lookup succeeded", () => {
		expect.hasAssertions();
		const lookup = new Map<string, string>([["#root", "<main>"]]);
		const element = lookup.get("#root");

		assertNonNullish(element, "#root is missing from the document");
		const markup = element.concat("</main>");
		expect(markup).toStrictEqual("<main></main>");
	});

	// packages/types/src/narrow.ts:991
	it("invariant — Guarding an index and its lookup in one function", () => {
		expect.hasAssertions();
		function at(items: readonly string[], index: number): string {
		  invariant(index >= 0 && index < items.length, "index out of range");
		  const item = items[index];
		  invariant(item !== undefined);
		  return item; // ✓ `string`, not `string | undefined`
		}

		const second = at(["a", "b"], 1);
		expect(second).toStrictEqual("b");
	});

	// packages/types/src/narrow.ts:1048
	it("assertGuard — The annotation that makes it work", () => {
		expect.hasAssertions();
		const assertString: Assertion<unknown, string> = assertGuard(isString);

		const raw: unknown = "hello";
		assertString(raw);
		const length = raw.length;
		expect(length).toStrictEqual(5);
	});

	// packages/types/src/narrow.ts:1061
	it("assertGuard — The mistake this doc exists to prevent", () => {
		expect.hasAssertions();
		const broken = assertGuard(isString); // ✗ un-annotated const
		const raw: unknown = "hello";

		// @ts-expect-error TS2775 — assertions require every name in the call target
		// to be declared with an explicit type annotation.
		broken(raw);

		// The check ran, but `raw` was never narrowed: `raw.length` here is an error.
		const kind = typeof raw;
		expect(kind).toStrictEqual("string");
	});

	// packages/types/src/narrow.ts:1132
	it("assert — Migrating a truthiness check", () => {
		expect.hasAssertions();
		const session: { readonly userId: string } | undefined = { userId: "u1" };

		assert(session, "no session");
		const userId = session.userId;
		expect(userId).toStrictEqual("u1");
	});

	// packages/types/src/narrow.ts:1197
	it("assertExists — Reading a config value, and the falsy-but-present case", () => {
		expect.hasAssertions();
		const config: { readonly port?: number; readonly retries?: number } = {
		  port: 8080,
		  retries: 0,
		};

		const port = assertExists(config.port);
		expect(port).toStrictEqual(8080);
		const retries = assertExists(config.retries);
		expect(retries).toStrictEqual(0);
	});
});
