/**
 * Copyright 2026 ResQ Systems, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @fileoverview Generated doctests for `packages/types/src/order.ts`.
 *
 * Every block below is a `ts doctest` fence lifted verbatim out of a JSDoc
 * example. Editing this file is pointless — edit the example it came from and
 * re-run the package's `doctest` script.
 */

// @generated by scripts/extract-doctests.ts from packages/types/src/order.ts — DO NOT EDIT.
// biome-ignore-all format: generated file — example text is reproduced verbatim from its JSDoc.
// biome-ignore-all lint: generated file — examples bind values purely to prove they type-check.

import { describe, expect, it } from "vitest";
import {
	type Order,
	type Ordering,
	alwaysEqual,
	arrayOf,
	clamp,
	combine,
	combineAll,
	fromCompare,
	isBetween,
	isGreaterThan,
	isGreaterThanOrEqualTo,
	isLessThan,
	isLessThanOrEqualTo,
	make,
	mapInput,
	max,
	min,
	orderBigInt,
	orderBoolean,
	orderDate,
	orderNumber,
	orderString,
	reverse,
	structOf,
	toEquivalence,
	tupleOf,
} from "../../order.js";
import { type Predicate } from "../../predicate.js";

describe("packages/types/src/order.ts", () => {
	// packages/types/src/order.ts:76
	it("Module — Sorting by one field, then another", () => {
		expect.hasAssertions();
		type Row = { readonly name: string; readonly age: number };

		const byAge = mapInput(orderNumber, (row: Row) => row.age);
		const byName = mapInput(orderString, (row: Row) => row.name);
		const byAgeThenName = combineAll([byAge, byName]);

		const rows: readonly Row[] = [
		  { name: "b", age: 30 },
		  { name: "a", age: 30 },
		  { name: "c", age: 20 },
		];

		const sorted = [...rows].sort(byAgeThenName).map((row) => row.name);
		expect(sorted).toStrictEqual(["c", "a", "b"]);
	});

	// packages/types/src/order.ts:127
	it("Ordering — The narrow type rejects a subtraction comparator", () => {
		expect.hasAssertions();
		const result: Ordering = orderNumber(1, 2);
		expect(result).toStrictEqual(-1);

		// @ts-expect-error — `a - b` is a `number`, not an `Ordering`.
		const bad: Order<number> = (a, b) => a - b;
	});

	// packages/types/src/order.ts:192
	it("Order — An order is already a `sort` comparator", () => {
		expect.hasAssertions();
		const compare: (a: number, b: number) => number = orderNumber;
		const sorted = [3, 1, 2].sort(compare);
		expect(sorted).toStrictEqual([1, 2, 3]);
	});

	// packages/types/src/order.ts:273
	it("make — Ordering by length", () => {
		expect.hasAssertions();
		const byLength = make<string>((self, that) => (self.length < that.length ? -1 : self.length > that.length ? 1 : 0));

		expect(byLength("aa", "b")).toStrictEqual(1);
		expect(byLength("b", "aa")).toStrictEqual(-1);
		expect(byLength("ab", "cd")).toStrictEqual(0);
		expect(byLength("same", "same")).toStrictEqual(0);
	});

	// packages/types/src/order.ts:325
	it("fromCompare — Locale-aware string ordering, done safely", () => {
		expect.hasAssertions();
		const byLocale = fromCompare<string>((self, that) => self.localeCompare(that));

		expect(byLocale("a", "b")).toStrictEqual(-1);
		expect(byLocale("b", "a")).toStrictEqual(1);
		expect(byLocale("a", "a")).toStrictEqual(0);

		const byAge = fromCompare<number>((self, that) => self - that);
		expect(byAge(30, 4)).toStrictEqual(1);

		// A `NaN` result is not an ordering; it collapses to `equal`.
		const broken = fromCompare<number>(() => Number.NaN);
		expect(broken(1, 2)).toStrictEqual(0);
	});

	// packages/types/src/order.ts:379
	it("alwaysEqual — The empty fold", () => {
		expect.hasAssertions();
		const nothing = alwaysEqual<string>();
		expect(nothing("a", "b")).toStrictEqual(0);

		expect(combineAll<string>([])("a", "b")).toStrictEqual(0);
	});

	// packages/types/src/order.ts:423
	it("reverse — Descending", () => {
		expect.hasAssertions();
		const descending = reverse(orderNumber);

		expect(descending(1, 2)).toStrictEqual(1);
		const sorted = [1, 3, 2].sort(descending);
		expect(sorted).toStrictEqual([3, 2, 1]);
	});

	// packages/types/src/order.ts:462
	it("combine — Rank, then name", () => {
		expect.hasAssertions();
		type Row = { readonly rank: number; readonly name: string };

		const byRank = mapInput(orderNumber, (row: Row) => row.rank);
		const byName = mapInput(orderString, (row: Row) => row.name);
		const byRankThenName = combine(byRank, byName);

		expect(byRankThenName({ rank: 1, name: "a" }, { rank: 1, name: "b" })).toStrictEqual(-1);
		expect(byRankThenName({ rank: 2, name: "a" }, { rank: 1, name: "b" })).toStrictEqual(1);
	});

	// packages/types/src/order.ts:511
	it("combineAll — Explicit precedence, in the order you wrote it", () => {
		expect.hasAssertions();
		type Row = { readonly rank: number; readonly name: string };

		const precedence = combineAll<Row>([
		  mapInput(orderNumber, (row: Row) => row.rank),
		  mapInput(orderString, (row: Row) => row.name),
		]);

		expect(precedence({ rank: 1, name: "b" }, { rank: 1, name: "a" })).toStrictEqual(1);
		expect(precedence({ rank: 0, name: "z" }, { rank: 1, name: "a" })).toStrictEqual(-1);
	});

	// packages/types/src/order.ts:583
	it("mapInput — Sorting records by a field", () => {
		expect.hasAssertions();
		type Row = { readonly age: number };

		const byAge = mapInput(orderNumber, (row: Row) => row.age);

		expect(byAge({ age: 20 }, { age: 30 })).toStrictEqual(-1);
		expect(byAge({ age: 30 }, { age: 30 })).toStrictEqual(0);
	});

	// packages/types/src/order.ts:633
	it("orderString — Machine ordering is case-sensitive", () => {
		expect.hasAssertions();
		expect(orderString("a", "b")).toStrictEqual(-1);
		expect(orderString("B", "a")).toStrictEqual(-1);
		const sorted = ["b", "A", "a"].sort(orderString);
		expect(sorted).toStrictEqual(["A", "a", "b"]);
	});

	// packages/types/src/order.ts:677
	it("orderNumber — `NaN` sorts first and compares equal to itself", () => {
		expect.hasAssertions();
		expect(orderNumber(1, 2)).toStrictEqual(-1);
		expect(orderNumber(0, -0)).toStrictEqual(0);
		expect(orderNumber(Number.NaN, Number.NaN)).toStrictEqual(0);
		expect(orderNumber(Number.NaN, Number.NEGATIVE_INFINITY)).toStrictEqual(-1);
		const sorted = [3, Number.NaN, 1].sort(orderNumber);
		expect(sorted).toStrictEqual([NaN, 1, 3]);
	});

	// packages/types/src/order.ts:717
	it("orderBoolean — Falsey first", () => {
		expect.hasAssertions();
		expect(orderBoolean(false, true)).toStrictEqual(-1);
		expect(orderBoolean(true, true)).toStrictEqual(0);
		const sorted = [true, false, true].sort(orderBoolean);
		expect(sorted).toStrictEqual([false, true, true]);
	});

	// packages/types/src/order.ts:746
	it("orderBigInt — Beyond safe-integer range", () => {
		expect.hasAssertions();
		expect(orderBigInt(1n, 2n)).toStrictEqual(-1);
		expect(orderBigInt(10n, 2n)).toStrictEqual(1);
		expect(orderBigInt(9007199254740993n, 9007199254740993n)).toStrictEqual(0);
	});

	// packages/types/src/order.ts:781
	it("orderDate — Invalid Dates sort first and compare equal", () => {
		expect.hasAssertions();
		const early = new Date("2020-01-01T00:00:00.000Z");
		const late = new Date("2024-01-01T00:00:00.000Z");
		const invalid = new Date("nope");

		expect(orderDate(early, late)).toStrictEqual(-1);
		expect(orderDate(late, early)).toStrictEqual(1);
		expect(orderDate(invalid, early)).toStrictEqual(-1);
		expect(orderDate(invalid, new Date("also nope"))).toStrictEqual(0);
	});

	// packages/types/src/order.ts:831
	it("tupleOf — Surname, then age", () => {
		expect.hasAssertions();
		const byPair = tupleOf([orderString, orderNumber]);

		expect(byPair(["a", 2], ["a", 1])).toStrictEqual(1);
		expect(byPair(["a", 1], ["b", 0])).toStrictEqual(-1);
		expect(byPair(["a", 1], ["a", 1])).toStrictEqual(0);
	});

	// packages/types/src/order.ts:892
	it("arrayOf — Shorter prefixes sort first", () => {
		expect.hasAssertions();
		const byNumbers = arrayOf(orderNumber);

		expect(byNumbers([1, 2], [1, 3])).toStrictEqual(-1);
		expect(byNumbers([1, 2], [1, 2, 0])).toStrictEqual(-1);
		expect(byNumbers([2], [1, 9, 9])).toStrictEqual(1);
		expect(byNumbers([], [])).toStrictEqual(0);
	});

	// packages/types/src/order.ts:959
	it("structOf — Rank, then name", () => {
		expect.hasAssertions();
		const byRankThenName = structOf({ rank: orderNumber, name: orderString });

		expect(byRankThenName({ rank: 1, name: "b" }, { rank: 1, name: "a" })).toStrictEqual(1);
		expect(byRankThenName({ rank: 0, name: "z" }, { rank: 1, name: "a" })).toStrictEqual(-1);
		expect(byRankThenName({ rank: 1, name: "a" }, { rank: 1, name: "a" })).toStrictEqual(0);
	});

	// packages/types/src/order.ts:971
	it("structOf — An integer-like key jumps the queue", () => {
		expect.hasAssertions();
		// Written name-first, but `Object.keys` yields ["2", "name"].
		const surprising = structOf({ name: orderString, 2: orderNumber });

		// `name` alone would answer -1; `2` answers 1 and is consulted first.
		expect(surprising({ name: "a", 2: 9 }, { name: "b", 2: 1 })).toStrictEqual(1);
	});

	// packages/types/src/order.ts:1054
	it("isLessThan — Composing with the guard algebra", () => {
		expect.hasAssertions();
		const under10: Predicate<number> = isLessThan(orderNumber)(10);

		expect(under10(9)).toStrictEqual(true);
		expect(under10(10)).toStrictEqual(false);
		const kept = [5, 10, 15].filter(under10);
		expect(kept).toStrictEqual([5]);
	});

	// packages/types/src/order.ts:1094
	it("isGreaterThan — Filtering above a threshold", () => {
		expect.hasAssertions();
		const over10 = isGreaterThan(orderNumber)(10);

		expect(over10(11)).toStrictEqual(true);
		expect(over10(10)).toStrictEqual(false);
		const kept = [5, 10, 15].filter(over10);
		expect(kept).toStrictEqual([15]);
	});

	// packages/types/src/order.ts:1130
	it("isLessThanOrEqualTo — An inclusive cap", () => {
		expect.hasAssertions();
		const atMost10 = isLessThanOrEqualTo(orderNumber)(10);

		expect(atMost10(10)).toStrictEqual(true);
		expect(atMost10(11)).toStrictEqual(false);
	});

	// packages/types/src/order.ts:1165
	it("isGreaterThanOrEqualTo — An inclusive floor", () => {
		expect.hasAssertions();
		const atLeast18 = isGreaterThanOrEqualTo(orderNumber)(18);

		expect(atLeast18(18)).toStrictEqual(true);
		expect(atLeast18(17)).toStrictEqual(false);
	});

	// packages/types/src/order.ts:1220
	it("isBetween — An inclusive band", () => {
		expect.hasAssertions();
		const inRange = isBetween(orderNumber)({ minimum: 1, maximum: 10 });

		expect(inRange(1)).toStrictEqual(true);
		expect(inRange(10)).toStrictEqual(true);
		expect(inRange(0)).toStrictEqual(false);
		expect(inRange(11)).toStrictEqual(false);

		// Inverted bounds describe an empty range.
		expect(isBetween(orderNumber)({ minimum: 10, maximum: 1 })(5)).toStrictEqual(false);
	});

	// packages/types/src/order.ts:1277
	it("min — Capping from above", () => {
		expect.hasAssertions();
		const atMost10 = min(orderNumber)(10);

		expect(atMost10(4)).toStrictEqual(4);
		expect(atMost10(42)).toStrictEqual(10);
	});

	// packages/types/src/order.ts:1315
	it("max — Flooring from below", () => {
		expect.hasAssertions();
		const atLeast0 = max(orderNumber)(0);

		expect(atLeast0(4)).toStrictEqual(4);
		expect(atLeast0(-7)).toStrictEqual(0);
	});

	// packages/types/src/order.ts:1367
	it("clamp — Pinning to a unit interval", () => {
		expect.hasAssertions();
		const toUnit = clamp(orderNumber)({ minimum: 0, maximum: 1 });

		expect(toUnit(-0.5)).toStrictEqual(0);
		expect(toUnit(0.5)).toStrictEqual(0.5);
		expect(toUnit(2)).toStrictEqual(1);

		// Inverted bounds resolve to `maximum` rather than throwing.
		expect(clamp(orderNumber)({ minimum: 10, maximum: 0 })(5)).toStrictEqual(0);
	});

	// packages/types/src/order.ts:1429
	it("toEquivalence — The kernel of a numeric order", () => {
		expect.hasAssertions();
		const sameNumber = toEquivalence(orderNumber);

		expect(sameNumber(1, 1)).toStrictEqual(true);
		expect(sameNumber(0, -0)).toStrictEqual(true);
		expect(sameNumber(Number.NaN, Number.NaN)).toStrictEqual(true);
		expect(sameNumber(1, 2)).toStrictEqual(false);
	});
});
