/**
 * Copyright 2026 ResQ Systems, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @fileoverview Generated doctests for `packages/types/src/predicate.ts`.
 *
 * Every block below is a `ts doctest` fence lifted verbatim out of a JSDoc
 * example. Editing this file is pointless — edit the example it came from and
 * re-run the package's `doctest` script.
 */

// @generated by scripts/extract-doctests.ts from packages/types/src/predicate.ts — DO NOT EDIT.
// biome-ignore-all format: generated file — example text is reproduced verbatim from its JSDoc.
// biome-ignore-all lint: generated file — examples bind values purely to prove they type-check.

import { describe, expect, it } from "vitest";
import { isBoolean, isNull, isNumber, isString } from "../../guards.js";
import {
	type Predicate,
	type Refinement,
	type TypeGuard,
	allOf,
	alwaysFalse,
	alwaysTrue,
	and,
	anyOf,
	arrayOf,
	compose,
	eqv,
	everyOf,
	exactlyOne,
	implies,
	lazy,
	mapInput,
	nand,
	noneOf,
	not,
	nullableOf,
	nullishOf,
	optionalOf,
	or,
	recordOf,
	refineOn,
	someOf,
	structOf,
	tupleOf,
} from "../../predicate.js";

describe("packages/types/src/predicate.ts", () => {
	// packages/types/src/predicate.ts:143
	it("Predicate — Reusing an `unknown` predicate at a narrower input type", () => {
		expect.hasAssertions();
		const isShort: Predicate<string> = (value) => value.length < 10;
		const anything: Predicate<string> = alwaysTrue;

		expect(isShort("hello")).toStrictEqual(true);
		expect(anything("hello")).toStrictEqual(true);
	});

	// packages/types/src/predicate.ts:190
	it("Predicate.Any — Holding predicates over unrelated domains", () => {
		const isShort: Predicate<string> = (value) => value.length < 10;
		const isEven: Predicate<number> = (value) => value % 2 === 0;

		const witness: readonly Predicate.Any[] = [isShort, isEven];
	});

	// packages/types/src/predicate.ts:224
	it("Predicate.In — Reading a predicate's domain back out", () => {
		type A = Predicate.In<Predicate<string>>;

		const witness: A = "value";
	});

	// packages/types/src/predicate.ts:270
	it("Refinement — Two guards over different domains", () => {
		expect.hasAssertions();
		const isNonEmpty: Refinement<string, string> = (value): value is string =>
		  value.length > 0;

		type Animal = "cat" | "dog";
		const isCat: Refinement<Animal, "cat"> = (value): value is "cat" => value === "cat";

		expect(isNonEmpty("")).toStrictEqual(false);
		expect(isCat("cat")).toStrictEqual(true);
	});

	// packages/types/src/predicate.ts:331
	it("Refinement.Any — Holding guards over unrelated domains", () => {
		const witness: readonly Refinement.Any[] = [isString, isNumber];
	});

	// packages/types/src/predicate.ts:361
	it("Refinement.In — Reading a guard's domain back out", () => {
		type Animal = "cat" | "dog";
		const isCat: Refinement<Animal, "cat"> = (value): value is "cat" => value === "cat";

		type A = Refinement.In<typeof isCat>;
		type U = Refinement.In<typeof isString>;

		const domain: A = "dog";
		const anything: U = 1;
	});

	// packages/types/src/predicate.ts:408
	it("Refinement.Out — Computing a result type from a guard", () => {
		type S = Refinement.Out<typeof isString>;
		type U = Refinement.Out<Refinement<unknown, 1 | 2>>;

		const proven: S = "value";
		const narrowed: U = 2;
	});

	// packages/types/src/predicate.ts:448
	it("Refinement.OutUnion — The union two guards prove", () => {
		type T = Refinement.OutUnion<[typeof isString, typeof isNumber]>;

		const witness: T = "value";
		const alsoWitness: T = 1;
	});

	// packages/types/src/predicate.ts:485
	it("Refinement.OutIntersection — The intersection two guards prove", () => {
		type T = Refinement.OutIntersection<
		  [TypeGuard<{ id: string }>, TypeGuard<{ n: number }>]
		>;

		const witness: T = { id: "a", n: 1 };
	});

	// packages/types/src/predicate.ts:524
	it("TypeGuard — A hand-written boundary guard", () => {
		expect.hasAssertions();
		const isPort: TypeGuard<number> = (value): value is number =>
		  typeof value === "number" && value > 0 && value < 65_536;

		expect(isPort(8080)).toStrictEqual(true);
		expect(isPort("8080")).toStrictEqual(false);
	});

	// packages/types/src/predicate.ts:694
	it("and — Requiring two conditions of one value", () => {
		expect.hasAssertions();
		const isPositive = (value: unknown): value is number =>
		  typeof value === "number" && value > 0;

		const isPositiveNumber = and(isNumber, isPositive);

		expect(isPositiveNumber(1)).toStrictEqual(true);
		expect(isPositiveNumber(-1)).toStrictEqual(false);
		expect(isPositiveNumber("1")).toStrictEqual(false);
	});

	// packages/types/src/predicate.ts:710
	it("and — The data-last form", () => {
		expect.hasAssertions();
		const isPositive = (value: unknown): value is number =>
		  typeof value === "number" && value > 0;

		const requirePositive = and(isPositive);
		const isPositiveNumber = requirePositive(isNumber);

		expect(isPositiveNumber(2)).toStrictEqual(true);
	});

	// packages/types/src/predicate.ts:725
	it("and — Adding a plain rule without losing the proof", () => {
		expect.hasAssertions();
		const isNonEmptyString = and(isString, (text: string) => text.length > 0);

		expect(isNonEmptyString("ada")).toStrictEqual(true);
		expect(isNonEmptyString("")).toStrictEqual(false);
		expect(isNonEmptyString(42)).toStrictEqual(false);

		// The `string` proof survived the plain rule, so `filter` still narrows.
		const mixed: readonly unknown[] = ["ada", "", 42];
		expect(mixed.filter(isNonEmptyString)).toStrictEqual(["ada"]);
	});

	// packages/types/src/predicate.ts:831
	it("or — Naming a union guard", () => {
		expect.hasAssertions();
		const isScalar = or(isString, isNumber);

		expect(isScalar("a")).toStrictEqual(true);
		expect(isScalar(1)).toStrictEqual(true);
		expect(isScalar(true)).toStrictEqual(false);
	});

	// packages/types/src/predicate.ts:898
	it("not — Subtracting from a union domain", () => {
		expect.hasAssertions();
		type Animal = "cat" | "dog" | "fish";
		const isCat: Refinement<Animal, "cat"> = (value): value is "cat" => value === "cat";

		const notCat = not(isCat);
		const notString = not(isString);

		expect(notCat("dog")).toStrictEqual(true);
		expect(notString(1)).toStrictEqual(true);
	});

	// packages/types/src/predicate.ts:965
	it("nand — Two mutually exclusive options", () => {
		expect.hasAssertions();
		type Creds = { readonly token?: string; readonly keyFile?: string };

		const hasToken: Predicate<Creds> = (c) => c.token !== undefined;
		const hasKeyFile: Predicate<Creds> = (c) => c.keyFile !== undefined;

		const notBoth = nand(hasToken, hasKeyFile);

		expect(notBoth({ token: "t" })).toStrictEqual(true);
		expect(notBoth({ token: "t", keyFile: "k" })).toStrictEqual(false);
	});

	// packages/types/src/predicate.ts:1032
	it("eqv — Two fields that must be set together", () => {
		expect.hasAssertions();
		type Window = { readonly start?: string; readonly end?: string };

		const hasStart: Predicate<Window> = (w) => w.start !== undefined;
		const hasEnd: Predicate<Window> = (w) => w.end !== undefined;

		const bothOrNeither = eqv(hasStart, hasEnd);

		expect(bothOrNeither({})).toStrictEqual(true);
		expect(bothOrNeither({ start: "a", end: "b" })).toStrictEqual(true);
		expect(bothOrNeither({ start: "a" })).toStrictEqual(false);
	});

	// packages/types/src/predicate.ts:1101
	it("implies — A conditional configuration rule", () => {
		expect.hasAssertions();
		type Conn = { readonly kind: string; readonly port?: number };

		const isTcp: Predicate<Conn> = (c) => c.kind === "tcp";
		const hasPort: Predicate<Conn> = (c) => c.port !== undefined;

		const portRequiredForTcp = implies(isTcp, hasPort);

		expect(portRequiredForTcp({ kind: "tcp", port: 1 })).toStrictEqual(true);
		expect(portRequiredForTcp({ kind: "tcp" })).toStrictEqual(false);
		expect(portRequiredForTcp({ kind: "unix" })).toStrictEqual(true);
	});

	// packages/types/src/predicate.ts:1155
	it("allOf — Requiring two shapes at once", () => {
		expect.hasAssertions();
		const isConfig = allOf(structOf({ host: isString }), structOf({ port: isNumber }));

		expect(isConfig({ host: "localhost", port: 80 })).toStrictEqual(true);
		expect(isConfig({ host: "localhost" })).toStrictEqual(false);
	});

	// packages/types/src/predicate.ts:1203
	it("anyOf — A JSON scalar guard", () => {
		expect.hasAssertions();
		const isJsonScalar = anyOf(isString, isNumber, isBoolean, isNull);

		expect(isJsonScalar("a")).toStrictEqual(true);
		expect(isJsonScalar(null)).toStrictEqual(true);
		expect(isJsonScalar({})).toStrictEqual(false);
	});

	// packages/types/src/predicate.ts:1257
	it("noneOf — Rejecting a set of members of a union", () => {
		expect.hasAssertions();
		type Animal = "cat" | "dog" | "fish";
		const isCat: Refinement<Animal, "cat"> = (value): value is "cat" => value === "cat";
		const isDog: Refinement<Animal, "dog"> = (value): value is "dog" => value === "dog";

		const isFish = noneOf(isCat, isDog);

		expect(isFish("fish")).toStrictEqual(true);
		expect(isFish("cat")).toStrictEqual(false);
	});

	// packages/types/src/predicate.ts:1319
	it("exactlyOne — Exactly one credential source", () => {
		expect.hasAssertions();
		type Creds = {
		  readonly token?: string;
		  readonly keyFile?: string;
		  readonly env?: string;
		};

		const hasOneCredential = exactlyOne<Creds>(
		  (c) => c.token !== undefined,
		  (c) => c.keyFile !== undefined,
		  (c) => c.env !== undefined,
		);

		expect(hasOneCredential({ token: "t" })).toStrictEqual(true);
		expect(hasOneCredential({ token: "t", env: "E" })).toStrictEqual(false);
		expect(hasOneCredential({})).toStrictEqual(false);
	});

	// packages/types/src/predicate.ts:1380
	it("everyOf — Folding a runtime-built rule set", () => {
		expect.hasAssertions();
		const minLengths = [1, 3, 5];
		const rules: readonly Predicate<string>[] = minLengths.map(
		  (n) => (value: string) => value.length >= n,
		);

		const isLongEnough = everyOf(rules);

		expect(isLongEnough("abcdef")).toStrictEqual(true);
		expect(isLongEnough("abcd")).toStrictEqual(false);
	});

	// packages/types/src/predicate.ts:1431
	it("someOf — Any of a runtime-built allow list", () => {
		expect.hasAssertions();
		const allowed = ["admin", "owner"];
		const rules: readonly Predicate<string>[] = allowed.map(
		  (role) => (value: string) => value === role,
		);

		const isAllowed = someOf(rules);

		expect(isAllowed("owner")).toStrictEqual(true);
		expect(isAllowed("guest")).toStrictEqual(false);
	});

	// packages/types/src/predicate.ts:1507
	it("compose — Proving a string, then refining it", () => {
		expect.hasAssertions();
		const isDigits = (value: string): value is `${number}` => /^\d+$/.test(value);
		const isNumericString = compose(isString, isDigits);

		expect(isNumericString("123")).toStrictEqual(true);
		expect(isNumericString("abc")).toStrictEqual(false);
		expect(isNumericString(123)).toStrictEqual(false);
	});

	// packages/types/src/predicate.ts:1565
	it("mapInput — Validating a field through a projection", () => {
		expect.hasAssertions();
		type User = { readonly email: string };

		const isValidEmail: Predicate<string> = (value) => value.includes("@");
		const hasValidEmail = mapInput(isValidEmail, (user: User) => user.email);

		expect(hasValidEmail({ email: "a@b.com" })).toStrictEqual(true);
		expect(hasValidEmail({ email: "nope" })).toStrictEqual(false);
	});

	// packages/types/src/predicate.ts:1614
	it("refineOn — Proving a discriminant field", () => {
		expect.hasAssertions();
		const kindIsString = refineOn("kind")(isString);
		const record: { kind: unknown } = { kind: "tcp" };

		if (kindIsString(record)) {
		  const shouted = record.kind.toUpperCase();
		  expect(shouted).toStrictEqual("TCP");
		}
	});

	// packages/types/src/predicate.ts:1665
	it("lazy — A recursive tree guard", () => {
		expect.hasAssertions();
		type Tree = { value: number; children: readonly Tree[] };

		const isTree: TypeGuard<Tree> = structOf({
		  value: isNumber,
		  children: arrayOf(lazy(() => isTree)),
		});

		expect(isTree({ value: 1, children: [{ value: 2, children: [] }] })).toStrictEqual(true);
	});

	// packages/types/src/predicate.ts:1708
	it("alwaysTrue — Defaulting an optional filter", () => {
		expect.hasAssertions();
		const options: { readonly filter?: Predicate<string> } = {};
		const filter: Predicate<string> = options.filter ?? alwaysTrue;

		expect(filter("anything")).toStrictEqual(true);
	});

	// packages/types/src/predicate.ts:1739
	it("alwaysFalse — An explicit deny-all", () => {
		expect.hasAssertions();
		const denyAll: Predicate<string> = alwaysFalse;

		expect(denyAll("anything")).toStrictEqual(false);
	});

	// packages/types/src/predicate.ts:1783
	it("arrayOf — An array of strings, and a sparse array that must not pass", () => {
		expect.hasAssertions();
		const isStrings = arrayOf(isString);

		expect(isStrings(["a", "b"])).toStrictEqual(true);
		expect(isStrings(["a", 1])).toStrictEqual(false);
		expect(isStrings(new Array(2))).toStrictEqual(false);
	});

	// packages/types/src/predicate.ts:1853
	it("recordOf — A header map, and a hidden key that must not slip through", () => {
		expect.hasAssertions();
		const isHeaders = recordOf(isString);

		expect(isHeaders({ "content-type": "application/json" })).toStrictEqual(true);

		const smuggled = {};
		Object.defineProperty(smuggled, "x", { value: 1, enumerable: false });

		expect(isHeaders(smuggled)).toStrictEqual(false);
	});

	// packages/types/src/predicate.ts:1921
	it("structOf — Validating a user payload", () => {
		expect.hasAssertions();
		const isUser = structOf({
		  id: isString,
		  tags: arrayOf(isString),
		  meta: optionalOf(isNumber),
		});

		expect(isUser({ id: "a", tags: ["x"] })).toStrictEqual(true);
		expect(isUser({ id: "a", tags: ["x"], meta: "no" })).toStrictEqual(false);
	});

	// packages/types/src/predicate.ts:1987
	it("tupleOf — A name/count pair", () => {
		expect.hasAssertions();
		const isPair = tupleOf(isString, isNumber);

		expect(isPair(["a", 1])).toStrictEqual(true);
		expect(isPair(["a"])).toStrictEqual(false);
		expect(isPair(["a", 1, true])).toStrictEqual(false);
	});

	// packages/types/src/predicate.ts:2032
	it("optionalOf — An optional numeric field", () => {
		expect.hasAssertions();
		const isMaybePort = optionalOf(isNumber);

		expect(isMaybePort(undefined)).toStrictEqual(true);
		expect(isMaybePort(null)).toStrictEqual(false);
	});

	// packages/types/src/predicate.ts:2070
	it("nullableOf — A nullable name field", () => {
		expect.hasAssertions();
		const isNullableName = nullableOf(isString);

		expect(isNullableName(null)).toStrictEqual(true);
		expect(isNullableName(undefined)).toStrictEqual(false);
	});

	// packages/types/src/predicate.ts:2109
	it("nullishOf — Accepting both absent and null", () => {
		expect.hasAssertions();
		const isMaybeName = nullishOf(isString);

		expect(isMaybeName(null)).toStrictEqual(true);
		expect(isMaybeName(undefined)).toStrictEqual(true);
		expect(isMaybeName(0)).toStrictEqual(false);
	});
});
