/**
 * Copyright 2026 ResQ Systems, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @fileoverview Generated doctests for `packages/types/src/union.ts`.
 *
 * Every block below is a `ts doctest` fence lifted verbatim out of a JSDoc
 * example. Editing this file is pointless — edit the example it came from and
 * re-run the package's `doctest` script.
 */

// @generated by scripts/extract-doctests.ts from packages/types/src/union.ts — DO NOT EDIT.
// biome-ignore-all format: generated file — example text is reproduced verbatim from its JSDoc.
// biome-ignore-all lint: generated file — examples bind values purely to prove they type-check.

import { describe, expect, it } from "vitest";
import {
	type DiscriminantKeys,
	type ExhaustiveHandlers,
	type MemberByTag,
	type MemberByTagOr,
	type MembersWithoutTag,
	type PartialHandlers,
	type TagMapOf,
	type TagValueOf,
	type TaggedGuard,
	type TaggedMember,
	type TaggedUnionOf,
	UnhandledTagError,
	byTag,
	hasTag,
	isTagged,
	isTaggedWith,
	isUnhandledTagError,
	matchTag,
	matchTagPartial,
} from "../../union.js";

describe("packages/types/src/union.ts", () => {
	// packages/types/src/union.ts:47
	it("Module — Routing on a tag without a fall-through hole", () => {
		expect.hasAssertions();
		type Shape =
			| { kind: "circle"; radius: number }
			| { kind: "square"; side: number }
			| { kind: "rect"; w: number; h: number };

		// ✗ compile error the moment Shape gains a member.
		const area = (s: Shape): number =>
			matchTag(s, "kind", {
				circle: (c) => Math.PI * c.radius ** 2, // c is the circle member
				square: (q) => q.side ** 2,
				rect: (r) => r.w * r.h,
			});

		expect(area({ kind: "square", side: 3 })).toStrictEqual(9);
	});

	// packages/types/src/union.ts:99
	it("DiscriminantKeys — Selecting the shared tag key", () => {
		expect.hasAssertions();
		type Shape =
			| { kind: "circle"; radius: number }
			| { kind: "square"; side: number };

		// "kind" — `radius` and `side` are not shared, so they never qualify.
		const witness: DiscriminantKeys<Shape> = "kind";

		expect(witness).toStrictEqual("kind");
	});

	// packages/types/src/union.ts:142
	it("TagValueOf — Listing every tag a union can carry", () => {
		expect.hasAssertions();
		type Shape =
			| { kind: "circle"; radius: number }
			| { kind: "square"; side: number }
			| { kind: "rect"; w: number; h: number };

		// "circle" | "square" | "rect"
		const witness: TagValueOf<Shape, "kind"> = "circle";

		expect(witness).toStrictEqual("circle");
	});

	// packages/types/src/union.ts:184
	it("MemberByTag — Naming one variant", () => {
		expect.hasAssertions();
		type Shape =
			| { kind: "circle"; radius: number }
			| { kind: "square"; side: number };

		type Circle = MemberByTag<Shape, "kind", "circle">;

		const witness: Circle = { kind: "circle", radius: 2 };

		expect(witness.radius).toStrictEqual(2);
	});

	// packages/types/src/union.ts:235
	it("MemberByTagOr — Keeping a guard's proof off the `never` floor", () => {
		expect.hasAssertions();
		type Shape =
			| { kind: "circle"; radius: number }
			| { kind: "square"; side: number };

		// A closed union behaves exactly like `MemberByTag`.
		const closed: MemberByTagOr<Shape, "kind", "circle"> = { kind: "circle", radius: 2 };

		// An open record stays inhabitable — plain `Extract` would bottom out at `never`.
		const open: MemberByTagOr<Record<"kind", PropertyKey>, "kind", "circle"> = { kind: "circle" };

		expect([closed.kind, open.kind]).toStrictEqual(["circle", "circle"]);
	});

	// packages/types/src/union.ts:292
	it("MembersWithoutTag — Naming the residual", () => {
		expect.hasAssertions();
		type Shape =
			| { kind: "circle"; radius: number }
			| { kind: "square"; side: number }
			| { kind: "rect"; w: number; h: number };

		// Everything the `circle` arm did not handle.
		type NotCircle = MembersWithoutTag<Shape, "kind", "circle">;

		const rest: NotCircle[] = [
			{ kind: "square", side: 3 },
			{ kind: "rect", w: 2, h: 5 },
		];

		expect(rest.map((member) => member.kind)).toStrictEqual(["square", "rect"]);
	});

	// packages/types/src/union.ts:313
	it("MembersWithoutTag — Handing the un-handled arms onward", () => {
		expect.hasAssertions();
		type Event =
			| { kind: "click"; x: number }
			| { kind: "key"; code: string }
			| { kind: "scroll"; dy: number };

		const route = (event: Event): string => {
			if (event.kind === "click") {
				return `click:${event.x}`;
			}
			// The narrowing the compiler performed, given a name a signature can use.
			const remaining: MembersWithoutTag<Event, "kind", "click"> = event;
			return remaining.kind;
		};

		expect(route({ kind: "scroll", dy: 9 })).toStrictEqual("scroll");
	});

	// packages/types/src/union.ts:364
	it("ExhaustiveHandlers — A table that cannot silently lose a variant", () => {
		expect.hasAssertions();
		type Shape =
			| { kind: "circle"; radius: number }
			| { kind: "square"; side: number }
			| { kind: "rect"; w: number; h: number };

		// ✗ compile error if any arm is dropped.
		const handlers: ExhaustiveHandlers<Shape, "kind", number> = {
			circle: (c) => c.radius, // c is narrowed, not Shape
			square: (q) => q.side,
			rect: (r) => r.w * r.h,
		};

		expect(handlers.rect({ kind: "rect", w: 4, h: 5 })).toStrictEqual(20);
	});

	// packages/types/src/union.ts:414
	it("PartialHandlers — Handling the variants you know about", () => {
		expect.hasAssertions();
		type WireEvent =
			| { type: "click"; x: number; y: number }
			| { type: "key"; code: string };

		// Every arm optional — `matchTagPartial` routes the rest to a fallback.
		const handlers: PartialHandlers<WireEvent, "type", string> = {
			key: (event) => event.code, // event is the key member, not WireEvent
		};

		expect(handlers.key?.({ type: "key", code: "Escape" })).toStrictEqual("Escape");
	});

	// packages/types/src/union.ts:457
	it("TagMapOf — Indexing variants by tag", () => {
		expect.hasAssertions();
		type Shape =
			| { kind: "circle"; radius: number }
			| { kind: "square"; side: number };

		type ByKind = TagMapOf<Shape, "kind">;

		const circle: ByKind["circle"] = { kind: "circle", radius: 2 };

		expect(circle.radius).toStrictEqual(2);
	});

	// packages/types/src/union.ts:501
	it("TaggedUnionOf — Declaring a union from its payloads", () => {
		expect.hasAssertions();
		// { type: "click"; x: number; y: number } | { type: "key"; code: string }
		type Event = TaggedUnionOf<"type", {
			click: { x: number; y: number };
			key: { code: string };
		}>;

		const witness: Event = { type: "click", x: 1, y: 2 };

		expect(witness.type).toStrictEqual("click");
	});

	// packages/types/src/union.ts:555
	it("hasTag — Entering from `unknown`", () => {
		expect.hasAssertions();
		const raw: unknown = JSON.parse(`{"kind":"circle","radius":2}`);

		// Inside the guard, `raw` is Record<"kind", PropertyKey>.
		const tag = hasTag(raw, "kind") ? String(raw.kind) : "untagged";
		expect(tag).toStrictEqual("circle");

		expect(hasTag({ kind: {} }, "kind")).toStrictEqual(false);
		expect(hasTag(null, "kind")).toStrictEqual(false);
	});

	// packages/types/src/union.ts:623
	it("TaggedMember — Member with payload, versus the bare shape from `unknown`", () => {
		expect.hasAssertions();
		type TimeoutError = { readonly _tag: "TimeoutError"; readonly ms: number };
		type ParseError = { readonly _tag: "ParseError"; readonly at: number };
		type AppError = TimeoutError | ParseError;

		// The input advertises `_tag`, so this is the whole member — `ms` included.
		const member: TaggedMember<AppError, "TimeoutError"> = { _tag: "TimeoutError", ms: 30 };

		// The input is `unknown`, so the honest proof is just the tag slot.
		const shape: TaggedMember<unknown, "TimeoutError"> = { _tag: "TimeoutError" };

		expect([member.ms, shape._tag]).toStrictEqual([30, "TimeoutError"]);
	});

	// packages/types/src/union.ts:677
	it("TaggedGuard — Naming a stored guard without losing the narrowing", () => {
		expect.hasAssertions();
		type TimeoutError = { readonly _tag: "TimeoutError"; readonly ms: number };
		type ParseError = { readonly _tag: "ParseError"; readonly at: number };

		const failures: ReadonlyArray<TimeoutError | ParseError> = [
			{ _tag: "TimeoutError", ms: 30 },
			{ _tag: "ParseError", at: 7 },
		];

		const isTimeout: TaggedGuard<"TimeoutError"> = isTagged("TimeoutError");

		// The annotation keeps `filter` narrowing to the member, so `.ms` is reachable.
		const waits = failures.filter(isTimeout).map((failure) => failure.ms);
		expect(waits).toStrictEqual([30]);
	});

	// packages/types/src/union.ts:728
	it("isTagged — Filtering one error variant out of a union", () => {
		expect.hasAssertions();
		type TimeoutError = { readonly _tag: "TimeoutError"; readonly ms: number };
		type ParseError = { readonly _tag: "ParseError"; readonly at: number };

		const failures: ReadonlyArray<TimeoutError | ParseError> = [
			{ _tag: "TimeoutError", ms: 30 },
			{ _tag: "ParseError", at: 7 },
		];

		const isTimeout = isTagged("TimeoutError");

		const waits = failures.filter(isTimeout).map((failure) => failure.ms);
		expect(waits).toStrictEqual([30]);
	});

	// packages/types/src/union.ts:783
	it("isTaggedWith — Minting a variant guard for an arbitrary discriminant", () => {
		expect.hasAssertions();
		type Shape =
			| { kind: "circle"; radius: number }
			| { kind: "square"; side: number };

		const shapes: Shape[] = [
			{ kind: "circle", radius: 2 },
			{ kind: "square", side: 3 },
		];

		const isCircle = isTaggedWith("kind", "circle");

		// Narrowed inside a block, and through `filter` into the array's element type.
		const radii = shapes.filter(isCircle).map((circle) => circle.radius);
		expect(radii).toStrictEqual([2]);
	});

	// packages/types/src/union.ts:841
	it("byTag — One key, many variant guards", () => {
		expect.hasAssertions();
		type Shape =
			| { kind: "circle"; radius: number }
			| { kind: "square"; side: number }
			| { kind: "rect"; w: number; h: number };

		const shapes: Shape[] = [
			{ kind: "circle", radius: 2 },
			{ kind: "rect", w: 4, h: 5 },
		];

		const byKind = byTag("kind");
		const isRect = byKind("rect");

		const areas = shapes.filter(isRect).map((r) => r.w * r.h); // r is the rect member
		expect(areas).toStrictEqual([20]);
	});

	// packages/types/src/union.ts:904
	it("UnhandledTagError — Reporting a variant this consumer predates", () => {
		expect.hasAssertions();
		type Shape =
			| { kind: "circle"; radius: number }
			| { kind: "square"; side: number };

		// A producer shipped a variant this consumer does not know about.
		const fromTheWire = { kind: "triangle", base: 1, height: 2 } as unknown as Shape;

		let reported = "none";
		try {
			matchTag(fromTheWire, "kind", {
				circle: (c) => c.radius,
				square: (q) => q.side,
			});
		} catch (error) {
			if (isUnhandledTagError(error)) reported = String(error.tag);
		}

		expect(reported).toStrictEqual("triangle");
	});

	// packages/types/src/union.ts:984
	it("isUnhandledTagError — Separating tag drift from ordinary failures", () => {
		expect.hasAssertions();
		const caught: unknown = new UnhandledTagError("triangle", "kind");

		const seen = isUnhandledTagError(caught) ? String(caught.tag) : "other";
		expect(seen).toStrictEqual("triangle");

		expect(isUnhandledTagError(new Error("boom"))).toStrictEqual(false);
	});

	// packages/types/src/union.ts:1090
	it("matchTag — Dispatching to an honest union of arm results", () => {
		expect.hasAssertions();
		type Shape =
			| { kind: "circle"; radius: number }
			| { kind: "square"; side: number }
			| { kind: "rect"; w: number; h: number };

		// number | string | null — the honest union, not `unknown`.
		const label = (shape: Shape) =>
			matchTag(shape, "kind", {
				circle: (c) => c.radius, // number
				square: (q) => `${q.side}`, // string
				rect: () => null, // null
			});

		expect(label({ kind: "square", side: 3 })).toStrictEqual("3");
		expect(label({ kind: "rect", w: 4, h: 5 })).toStrictEqual(null);
	});

	// packages/types/src/union.ts:1162
	it("matchTagPartial — Handling the known tags, routing the rest", () => {
		expect.hasAssertions();
		type Shape =
			| { kind: "circle"; radius: number }
			| { kind: "square"; side: number };

		// number | string — the arms' results plus the fallback's.
		const size = (shape: Shape) =>
			matchTagPartial(shape, "kind", { circle: (c) => c.radius }, () => "unknown");

		expect(size({ kind: "circle", radius: 2 })).toStrictEqual(2);
		expect(size({ kind: "square", side: 3 })).toStrictEqual("unknown");
	});
});
