name: CI

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/prepare
      - run: bun run build

  storybook:
    name: Storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/prepare
      - run: bun run build-storybook

  biome:
    name: Biome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/prepare
      - run: bunx biome ci .

  lint_knip:
    name: Lint Knip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/prepare
      - run: bun run lint:knip

  lint_markdown:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/prepare
      - run: bun lint:md

  lint_spelling:
    name: Lint Spelling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/prepare
      - run: bun lint:spelling

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/prepare
      - run: bun test --coverage
      - if: always()
        name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5

  type_check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/prepare
      - run: bun tsc
